use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::cell::RefCell;
use std::rc::Rc;
use std::time::Instant;

use serde_json::{Value, json};
use sha1::Digest;

use crate::{AnalyzeDiagnostic, LeekWarsContext, LeekWarsEntity, LeekWarsState, Outcome, Scenario};
use crate::registers::RegisterManagerRc;
use crate::world_map::{Rng, WorldMap};

#[derive(Debug, Default)]
pub struct Generator {
    pub verbose: bool,
    pub signature_files: Vec<PathBuf>,
    pub register_manager: Option<RegisterManagerRc>,
    pub trace_entity: Option<i64>,
}

impl Generator {
    pub fn new() -> Self {
        let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
        Self {
            verbose: false,
            signature_files: default_signature_files(&cwd),
            register_manager: None,
            trace_entity: None,
        }
    }

    /// Run the scenario using the in-repo Rust VM and leekscript compiler.
    pub fn run_scenario_from_file(&self, scenario_path: impl AsRef<Path>) -> miette::Result<Outcome> {
        let scenario_path = scenario_path.as_ref();
        let src = fs::read_to_string(scenario_path)
            .map_err(|e| miette::miette!("failed to read scenario `{}`: {e}", scenario_path.display()))?;
        let scenario = parse_scenario_from_path(scenario_path, &src)?;

        let scenario_dir = scenario_path.parent().unwrap_or(Path::new("."));
        let generator_root = scenario_path
            .ancestors()
            .find(|p| p.file_name().and_then(|s| s.to_str()) == Some("leek-wars-generator"))
            .unwrap_or(scenario_dir);

        self.run_scenario(&scenario, scenario_dir, generator_root)
    }

    pub fn run_scenario(
        &self,
        scenario: &Scenario,
        scenario_dir: impl AsRef<Path>,
        generator_root: impl AsRef<Path>,
    ) -> miette::Result<Outcome> {
        let scenario_dir = scenario_dir.as_ref();
        let generator_root = generator_root.as_ref();

        let mut analyze_time_ms: i64 = 0;
        let mut exec_time_ms: i64 = 0;
        let mut ai_logs: BTreeMap<String, Value> = BTreeMap::new();
        let mut ai_run: BTreeMap<String, Value> = BTreeMap::new();

        let weapons = load_weapons_db(generator_root);
        let chips = load_chips_db(generator_root);
        let summons = load_summons_db(generator_root);
        let mut rng_state: i64 = scenario
            .random_seed
            .unwrap_or(0)
            as i64;
        let mut id_map: std::collections::HashMap<i32, i64> = std::collections::HashMap::new();
        if cfg!(feature = "java-parity") {
            let mut next: i64 = 0;
            for team in &scenario.entities {
                for e in team {
                    id_map.insert(e.id, next);
                    next += 1;
                }
            }
        }

        let mut turn_order: Vec<i64> = Vec::new();
        for team in &scenario.entities {
            for e in team {
                let id = if cfg!(feature = "java-parity") {
                    *id_map.get(&e.id).unwrap_or(&(e.id as i64))
                } else {
                    e.id as i64
                };
                turn_order.push(id);
            }
        }
        let next_entity_id = turn_order.iter().copied().max().unwrap_or(0);
        let max_ops_per_entity: Option<u64> = scenario
            .max_operations_per_entity
            .and_then(|v| u64::try_from(v.max(0)).ok());
        let max_ram_quads: Option<u64> = json_i64_opt(&scenario.extra, "max_ram_quads")
            .and_then(|v| u64::try_from(v.max(0)).ok());
        // World creation:
        // - In parity mode: ignore scenario map/cells and generate a random world + placements.
        // - Otherwise: honor scenario.map if present, falling back to an empty default world.
        let (map, placements) = if cfg!(feature = "java-parity") {
            // If the parity harness provides a reference outcome (generated by the reference generator),
            // use its world directly to isolate combat-rule differences.
            if let Ok(path) = std::env::var("LW_REFERENCE_OUTCOME") {
                let Ok(src) = std::fs::read_to_string(&path) else {
                    return Err(miette::miette!("failed to read LW_REFERENCE_OUTCOME at {path}"));
                };
                let Ok(v) = serde_json::from_str::<serde_json::Value>(&src) else {
                    return Err(miette::miette!("failed to parse LW_REFERENCE_OUTCOME JSON at {path}"));
                };
                let fight = v.get("fight").ok_or_else(|| miette::miette!("reference outcome missing fight"))?;
                let mapv = fight.get("map").ok_or_else(|| miette::miette!("reference outcome missing fight.map"))?;
                let width = mapv.get("width").and_then(|x| x.as_i64()).unwrap_or(18) as i32;
                let height = mapv.get("height").and_then(|x| x.as_i64()).unwrap_or(18) as i32;
                let map_type = mapv.get("type").and_then(|x| x.as_i64()).unwrap_or(-1) as i32;
                let mut m = WorldMap::new(width, height);
                m.map_type = map_type;
                if let Some(obs) = mapv.get("obstacles").and_then(|o| o.as_object()) {
                    for (k, vv) in obs {
                        let Ok(cell_id) = k.parse::<i32>() else { continue };
                        let size = vv.as_i64().unwrap_or(1) as i32;
                        if size <= 0 {
                            continue;
                        }
                        // Anchor obstacle.
                        m.set_obstacle(cell_id, 1, size);
                        if size == 2 {
                            if let Some(id2) = m.get_cell_by_dir(cell_id, crate::world_map::Dir::East) {
                                m.set_obstacle(id2, 0, -1);
                            }
                            if let Some(id3) = m.get_cell_by_dir(cell_id, crate::world_map::Dir::South) {
                                m.set_obstacle(id3, 0, -2);
                                if let Some(id4) = m.get_cell_by_dir(id3, crate::world_map::Dir::East) {
                                    m.set_obstacle(id4, 0, -3);
                                }
                            }
                        }
                    }
                }
                // Placements are taken from the reference `leeks[].cellPos` by fight id.
                let mut p = vec![0i32; (scenario.entities.iter().map(|t| t.len()).sum::<usize>()).max(1)];
                if let Some(leeks) = fight.get("leeks").and_then(|x| x.as_array()) {
                    for l in leeks {
                        let Some(fid) = l.get("id").and_then(|x| x.as_i64()) else { continue };
                        let Some(cell) = l.get("cellPos").and_then(|x| x.as_i64()) else { continue };
                        if let (Ok(fid), Ok(cell)) = (usize::try_from(fid), i32::try_from(cell)) {
                            if fid < p.len() {
                                p[fid] = cell;
                            }
                        }
                    }
                }
                (m, Some(p))
            } else {
                let mut rng = Rng::new(rng_state);
                let obstacle_count = rng.int_inclusive(30, 80);
                let team_sizes: Vec<usize> = scenario.entities.iter().map(|t| t.len()).collect();
                // Reference uses CONTEXT_TEST (0) for this scenario.
                let (m, p, rng2) = WorldMap::generate_random(rng, 0, 18, 18, obstacle_count, &team_sizes);
                rng_state = rng2.n;
                (m, Some(p))
            }
        } else {
            let mut width = 18;
            let mut height = 18;
            let mut obstacles: Vec<i32> = Vec::new();
            if let Some(mapv) = scenario.map.as_ref() {
                width = mapv.get("width").and_then(|v| v.as_i64()).unwrap_or(18) as i32;
                height = mapv.get("height").and_then(|v| v.as_i64()).unwrap_or(18) as i32;
                obstacles = mapv
                    .get("obstacles")
                    .and_then(|v| v.as_array())
                    .map(|arr| arr.iter().filter_map(|x| x.as_i64()).filter_map(|x| i32::try_from(x).ok()).collect())
                    .unwrap_or_default();
            }
            let mut m = WorldMap::new(width, height);
            for oid in obstacles {
                m.set_obstacle(oid, 1, 1);
            }
            (m, None)
        };

        let state = Rc::new(RefCell::new(LeekWarsState {
            entities: self.build_vm_entities_with_id_map(scenario, &id_map),
            say_log: Vec::new(),
            fight_actions: Vec::new(),
            map,
            weapons,
            chips,
            summons,
            register_manager: self.register_manager.clone(),
            next_effect_instance_id: 0,
            turn_order,
            next_entity_id,
            rng_state,
            team_chip_cooldowns: std::collections::HashMap::new(),
        }));
        // Apply placements (parity mode).
        if let Some(p) = placements {
            let mut st = state.borrow_mut();
            // Reference assigns placements in team/entity iteration order (NOT turn order).
            let mut idx = 0usize;
            for team in &scenario.entities {
                for ent in team {
                    let eid = *id_map.get(&ent.id).unwrap_or(&(ent.id as i64));
                    if let (Some(&cell), Some(e)) = (p.get(idx), st.entities.get_mut(&eid)) {
                        e.cell = cell as i64;
                    }
                    idx += 1;
                }
            }
        }

        // Compute starting order (parity mode) based on per-team frequency, consuming RNG.
        if cfg!(feature = "java-parity") {
            let mut st = state.borrow_mut();
            st.turn_order = compute_start_order_for_scenario(scenario, &id_map, &mut st.rng_state);
        }

        // Snapshot initial cells (for parity-friendly metadata output).
        let initial_cells: std::collections::HashMap<i64, i64> = {
            let st = state.borrow();
            st.entities.iter().map(|(id, e)| (*id, e.cell)).collect()
        };

        // START_FIGHT
        state.borrow_mut().fight_actions.push(json!([0]));

        // Apply initial chip cooldowns.
        {
            let mut st = state.borrow_mut();
            // Pre-clone chips db to avoid borrow conflicts while mutating entities.
            let chips_db = st.chips.clone();
            // Collect (entity_id, team, chips[]) so we can update cooldowns without nested borrows.
            let plans: Vec<(i64, i64, Vec<i64>)> = st
                .entities
                .values()
                .map(|e| (e.id, e.team, e.chips.clone()))
                .collect();

            for (eid, team, chips) in plans {
                for chip_item in chips {
                    let Some(def) = chips_db.get(&chip_item).cloned() else { continue };
                    if def.initial_cooldown <= 0 {
                        continue;
                    }
                    if def.team_cooldown {
                        st.team_chip_cooldowns
                            .insert((team, def.template.as_i64()), def.initial_cooldown);
                    } else if let Some(e) = st.entities.get_mut(&eid) {
                        e.chip_cooldowns
                            .insert(def.template.as_i64(), def.initial_cooldown);
                    }
                }
            }
        }

        let max_turns = scenario.max_turns.unwrap_or(64).max(1);

        // Pre-resolve AI paths and compile once per entity (massive speedup for multi-turn loops).
        let mut compiled: std::collections::HashMap<i64, leekscript::vm::CompiledChunk> =
            std::collections::HashMap::new();
        for team in &scenario.entities {
            for e in team {
                let Some(ai_rel) = e.ai.as_deref() else { continue };
                let mut ai_path = scenario_dir.join(ai_rel);
                if !ai_path.exists() {
                    ai_path = generator_root.join(ai_rel);
                }
                if !ai_path.exists() {
                    ai_path = PathBuf::from(ai_rel);
                }

                // Analyze once.
                let start = Instant::now();
                let diags = self.analyze_ai_file(generator_root, &ai_path)?;
                analyze_time_ms += start.elapsed().as_millis() as i64;
                if !diags.is_empty() {
                    ai_logs.insert(e.id.to_string(), serde_json::to_value(&diags).unwrap_or(Value::Null));
                }

                // Compile once (with includes + custom native mapping).
                let canon_entry =
                    fs::canonicalize(&ai_path).map_err(|er| miette::miette!("invalid entry {}: {er}", ai_path.display()))?;
                let canon_root =
                    fs::canonicalize(generator_root).unwrap_or_else(|_| generator_root.to_path_buf());
                let chunk = leekscript::vm::compile_chunk_v4_with_includes_and_native_id_fn(
                    &canon_root,
                    &canon_entry,
                    crate::vm::native_id,
                )
                .map_err(|er| miette::miette!("{er}"))?;
                let key = if cfg!(feature = "java-parity") {
                    *id_map.get(&e.id).unwrap_or(&(e.id as i64))
                } else {
                    e.id as i64
                };
                compiled.insert(key, chunk);
            }
        }

        let mut turns_run: i32 = 0;
        for turn in 1..=max_turns {
            turns_run = turn;
            // Do not emit NEW_TURN for the first turn.
            if turn > 1 {
                state.borrow_mut().fight_actions.push(json!([6, turn]));
            }

            // Tick cooldowns/effects at start of turn (parity building blocks).
            {
                let mut st = state.borrow_mut();
                crate::vm::tick_chip_cooldowns_public(&mut st);
                crate::vm::tick_effects_start_turn_public(&mut st);
            }

            // Refresh TP/MP at the start of the turn (baseline policy).
            {
                let mut st = state.borrow_mut();
                for e in st.entities.values_mut() {
                    if e.life > 0 {
                        // Apply derived TP/MP modifiers (e.g. shackles) before refresh.
                        crate::vm::combat::recompute_derived_buffs(e);
                        let max_tp = (e.max_tp + e.tp_bonus).max(0);
                        let max_mp = (e.max_mp + e.mp_bonus).max(0);
                        e.tp = max_tp;
                        e.mp = max_mp;
                    }
                }
            }

            let order = state.borrow().turn_order.clone();
            for &entity_id in &order {
                // Skip dead entities.
                let alive = {
                    let st = state.borrow();
                    st.entities
                        .get(&entity_id)
                        .map(|e| e.life > 0)
                        .unwrap_or(false)
                };
                if !alive {
                    continue;
                }

                let Some(chunk) = compiled.get(&entity_id).cloned() else { continue };

                let run_start = Instant::now();
                state.borrow_mut().fight_actions.push(json!([7, entity_id]));
                let run = self.run_ai_chunk(
                    chunk,
                    entity_id as i32,
                    state.clone(),
                    max_ops_per_entity,
                    max_ram_quads,
                );
                exec_time_ms += run_start.elapsed().as_millis() as i64;
                // Run tracing: store per-turn VM info for one entity; otherwise keep first-turn-only.
                if let Ok(v) = run {
                    if self.trace_entity == Some(entity_id) {
                        let entry = ai_run
                            .entry(entity_id.to_string())
                            .or_insert_with(|| serde_json::Value::Array(Vec::new()));
                        if let serde_json::Value::Array(arr) = entry {
                            arr.push(json!({"turn": turn, "run": v}));
                        } else {
                            // If something else wrote a non-array, overwrite with a per-turn trace.
                            ai_run.insert(entity_id.to_string(), serde_json::Value::Array(vec![json!({"turn": turn, "run": v})]));
                        }
                    } else if turn == 1 {
                        ai_run.insert(entity_id.to_string(), v);
                    }
                }

                // Reference END_TURN reports max TP/MP (not remaining).
                let (tp, mp) = {
                    let st = state.borrow();
                    let me = st.entities.get(&entity_id);
                    (
                        me.map(|e| e.max_tp).unwrap_or(0),
                        me.map(|e| e.max_mp).unwrap_or(0),
                    )
                };
                state.borrow_mut().fight_actions.push(json!([8, entity_id, tp, mp]));
            }

            // Stop early if only one team has living entities.
            let teams_alive: std::collections::HashSet<i64> = {
                let st = state.borrow();
                st.entities
                    .values()
                    .filter(|e| e.life > 0)
                    .map(|e| e.team)
                    .collect()
            };
            if teams_alive.len() <= 1 {
                break;
            }
        }

        let winner_team: i64 = {
            let st = state.borrow();
            let alive: std::collections::HashSet<i64> =
                st.entities.values().filter(|e| e.life > 0).map(|e| e.team).collect();
            if alive.len() == 1 {
                *alive.iter().next().unwrap()
            } else {
                0
            }
        };

        // END_FIGHT: reference action stream doesn't include an explicit end marker.
        if !cfg!(feature = "java-parity") {
            state.borrow_mut().fight_actions.push(json!([4]));
        }

        // Save registers (reference behavior): persist for non-summon entities when modified or new.
        if let Some(mgr) = self.register_manager.as_ref() {
            let st = state.borrow();
            for (id, e) in &st.entities {
                if e.is_summon {
                    continue;
                }
                let Some(regs) = e.registers.as_ref() else {
                    continue;
                };
                if regs.is_modified() || regs.is_new() {
                    mgr.save_registers(*id, &regs.to_json_string(), regs.is_new());
                }
            }
        }

        let fight_actions = state.borrow().fight_actions.clone();
        let map_snapshot = state.borrow().map.clone();
        let fight = self.build_fight_skeleton_with_actions(scenario, &map_snapshot, &id_map, &initial_cells, fight_actions);
        let mut logs = json!({
            "ai": ai_logs,
            "ai_run": ai_run,
        });
        // Canonical outcome hash: sha1 of raw action stream JSON (stable across object key ordering).
        if let Some(actions) = fight.get("actions") {
            let s = serde_json::to_string(actions).unwrap_or_default();
            let hash = sha1::Sha1::digest(s.as_bytes());
            let hex = format!("{hash:x}");
            if let Some(obj) = logs.as_object_mut() {
                obj.insert("outcome_hash_sha1".into(), json!(hex));
            }
        }

        Ok(Outcome {
            fight,
            logs,
            winner: winner_team as i32,
            duration: turns_run,
            analyze_time: analyze_time_ms,
            compilation_time: 0,
            execution_time: exec_time_ms,
        })
    }

    pub fn analyze_ai_file(
        &self,
        project_root: impl AsRef<Path>,
        path: impl AsRef<Path>,
    ) -> miette::Result<Vec<AnalyzeDiagnostic>> {
        let project_root = project_root.as_ref();
        let path = path.as_ref();
        let canon_entry = fs::canonicalize(path)
            .map_err(|e| miette::miette!("invalid entry {}: {e}", path.display()))?;
        let canon_root = fs::canonicalize(project_root).unwrap_or_else(|_| project_root.to_path_buf());
        let lang = leekscript::LanguageOptions::default();

        let prep = leekscript::prepare_merged_check_unit(
            &canon_root,
            &canon_entry,
            lang,
            &self.signature_files,
            None,
        )
        .map_err(|e| miette::miette!("{e}"))?;

        let parsed = if prep.use_signature_grammar {
            leekscript::parse_signature_doc_with_recovery(&prep.combined, prep.resolved)
                .map_err(|e| miette::miette!("{e:?}"))?
        } else {
            leekscript::parse_doc_or_recover(&prep.combined, prep.resolved)
                .map_err(|e| miette::miette!("{e:?}"))?
        };

        Ok(parsed
            .errors
            .into_iter()
            .map(|e| AnalyzeDiagnostic {
                message: format!("{e:?}"),
            })
            .collect())
    }

    fn build_fight_skeleton(
        &self,
        scenario: &Scenario,
        map: &crate::world_map::WorldMap,
        id_map: &std::collections::HashMap<i32, i64>,
        initial_cells: &std::collections::HashMap<i64, i64>,
    ) -> Value {
        let mut leeks: Vec<Value> = Vec::new();
        for team in &scenario.entities {
            for e in team {
                let mut obj = serde_json::Map::new();
                let fid = if cfg!(feature = "java-parity") {
                    *id_map.get(&e.id).unwrap_or(&(e.id as i64))
                } else {
                    e.id as i64
                };
                obj.insert("id".into(), json!(fid));
                if let Some(level) = e.level {
                    obj.insert("level".into(), json!(level));
                }
                obj.insert("team".into(), json!(e.team));
                obj.insert("name".into(), json!(e.name));
                obj.insert("farmer".into(), json!(e.farmer));
                obj.insert("type".into(), json!(e.r#type));
                let scenario_cell = e.cell.unwrap_or(0) as i64;
                let cell_pos = if cfg!(feature = "java-parity") {
                    *initial_cells.get(&fid).unwrap_or(&scenario_cell)
                } else {
                    scenario_cell
                };
                obj.insert("cellPos".into(), json!(cell_pos));
                obj.insert("weapons".into(), json!(e.weapons));
                obj.insert("chips".into(), json!(e.chips));
                // Add baseline combat stats when present; helps replay/snapshot reconstruction.
                if let Some(life) = json_i64_opt(&e.extra, "life") {
                    obj.insert("life".into(), json!(life));
                }
                if let Some(tp) = json_i64_opt(&e.extra, "tp") {
                    obj.insert("tp".into(), json!(tp));
                }
                if let Some(mp) = json_i64_opt(&e.extra, "mp") {
                    obj.insert("mp".into(), json!(mp));
                }
                leeks.push(Value::Object(obj));
            }
        }

        let obstacles = if cfg!(feature = "java-parity") {
            // Reference JSON uses a map cell_id -> size (1 or 2) for obstacle anchors.
            let mut m = serde_json::Map::new();
            for c in &map.cells {
                if c.walkable {
                    continue;
                }
                if c.obstacle_size <= 0 {
                    continue;
                }
                m.insert(c.id.to_string(), json!(c.obstacle_size));
            }
            Value::Object(m)
        } else {
            let v: Vec<i32> = map
                .cells
                .iter()
                .filter(|c| !c.walkable)
                .map(|c| c.id)
                .collect();
            json!(v)
        };

        // Keep the same top-level keys as the reference JSON shape.
        json!({
            "leeks": leeks,
            "map": {
                "width": map.width,
                "height": map.height,
                "type": map.map_type,
                "obstacles": obstacles,
            },
            "actions": [],
            "dead": {},
            "ops": {},
        })
    }

    #[allow(dead_code)]
    fn run_ai_file(
        &self,
        project_root: &Path,
        path: &Path,
        self_id: i32,
        state: Rc<RefCell<LeekWarsState>>,
    ) -> miette::Result<Value> {
        let canon_entry =
            fs::canonicalize(path).map_err(|e| miette::miette!("invalid entry {}: {e}", path.display()))?;
        let canon_root =
            fs::canonicalize(project_root).unwrap_or_else(|_| project_root.to_path_buf());

        let chunk = leekscript::vm::compile_chunk_v4_with_includes_and_native_id_fn(
            &canon_root,
            &canon_entry,
            crate::vm::native_id,
        )
        .map_err(|e| miette::miette!("{e}"))?;

        let mut vm = leekscript::vm::Vm::from_compiled_chunk(chunk)
            .map_err(|e| miette::miette!("{e}"))?;
        vm.set_natives(crate::vm::default_natives());
        vm.set_host(Box::new(LeekWarsContext {
            self_id: self_id as i64,
            state,
        }));

        let out = vm.run();
        match out {
            Ok(v) => Ok(json!({
                "ok": true,
                "result": value_to_json(&v),
                "operations": vm.operations,
            })),
            Err(e) => Ok(json!({
                "ok": false,
                "error": e.to_string(),
                "operations": vm.operations,
            })),
        }
    }

    fn run_ai_chunk(
        &self,
        chunk: leekscript::vm::CompiledChunk,
        self_id: i32,
        state: Rc<RefCell<LeekWarsState>>,
        max_operations: Option<u64>,
        max_ram_quads: Option<u64>,
    ) -> miette::Result<Value> {
        let mut vm = leekscript::vm::Vm::from_compiled_chunk(chunk)
            .map_err(|e| miette::miette!("{e}"))?;
        vm.set_natives(crate::vm::default_natives());
        vm.set_host(Box::new(LeekWarsContext {
            self_id: self_id as i64,
            state,
        }));
        // Budgets (Scenario-driven). `None` means "use VM defaults".
        if let Some(limit) = max_operations {
            vm.max_operations = Some(limit);
        }
        if let Some(limit) = max_ram_quads {
            vm.max_ram_quads = Some(limit);
        }

        let out = vm.run();
        match out {
            Ok(v) => Ok(json!({
                "ok": true,
                "result": value_to_json(&v),
                "operations": vm.operations,
                "ram_bytes": vm.ram_bytes(),
            })),
            Err(e) => Ok(json!({
                "ok": false,
                "error": e.to_string(),
                "operations": vm.operations,
                "ram_bytes": vm.ram_bytes(),
            })),
        }
    }

    fn build_vm_entities(
        &self,
        scenario: &Scenario,
    ) -> std::collections::HashMap<i64, LeekWarsEntity> {
        self.build_vm_entities_with_id_map(scenario, &std::collections::HashMap::new())
    }

    fn build_vm_entities_with_id_map(
        &self,
        scenario: &Scenario,
        id_map: &std::collections::HashMap<i32, i64>,
    ) -> std::collections::HashMap<i64, LeekWarsEntity> {
        let mut out = std::collections::HashMap::new();
        for team in &scenario.entities {
            for e in team {
                let life = json_i64_opt(&e.extra, "life").unwrap_or(0);
                let strength = json_i64_opt(&e.extra, "strength").unwrap_or(0);
                let agility = json_i64_opt(&e.extra, "agility").unwrap_or(0);
                let magic = json_i64_opt(&e.extra, "magic").unwrap_or(0);
                let science = json_i64_opt(&e.extra, "science").unwrap_or(0);
                let wisdom = json_i64_opt(&e.extra, "wisdom").unwrap_or(0);
                let resistance = json_i64_opt(&e.extra, "resistance").unwrap_or(0);
                let power = json_i64_opt(&e.extra, "power").unwrap_or(0);
                let tp = json_i64_opt(&e.extra, "tp").unwrap_or(0);
                let mp = json_i64_opt(&e.extra, "mp").unwrap_or(0);
                let cell = e.cell.unwrap_or(0) as i64;
                let id: i64 = if cfg!(feature = "java-parity") {
                    *id_map.get(&e.id).unwrap_or(&(e.id as i64))
                } else {
                    e.id as i64
                };
                out.insert(
                    id,
                    LeekWarsEntity {
                        id,
                        name: e.name.clone(),
                        team: e.team as i64,
                        cell,
                        life,
                        total_life: life,
                        strength,
                        agility,
                        magic,
                        science,
                        wisdom,
                        resistance,
                        power,
                        tp,
                        mp,
                        max_tp: tp,
                        max_mp: mp,
                        weapons: if cfg!(feature = "java-parity")
                            && std::env::var("LW_REFERENCE_OUTCOME").is_ok()
                        {
                            Vec::new()
                        } else {
                            e.weapons.iter().map(|w| *w as i64).collect()
                        },
                        chips: if cfg!(feature = "java-parity")
                            && std::env::var("LW_REFERENCE_OUTCOME").is_ok()
                        {
                            Vec::new()
                        } else {
                            e.chips.iter().map(|c| *c as i64).collect()
                        },
                        equipped_weapon: None,
                        registers: None,
                        is_summon: false,
                        chip_cooldowns: std::collections::HashMap::new(),
                        item_uses: std::collections::HashMap::new(),
                        effects: Vec::new(),
                        shield_abs: 0,
                        shield_rel_percent: 0,
                        strength_bonus: 0,
                        mp_bonus: 0,
                        tp_bonus: 0,
                        damage_return: 0,
                        state_unhealable: false,
                        state_invincible: false,
                        state_static: false,
                    },
                );
            }
        }
        out
    }

    fn build_fight_skeleton_with_actions(
        &self,
        scenario: &Scenario,
        map: &crate::world_map::WorldMap,
        id_map: &std::collections::HashMap<i32, i64>,
        initial_cells: &std::collections::HashMap<i64, i64>,
        actions: Vec<Value>,
    ) -> Value {
        let mut fight = match self.build_fight_skeleton(scenario, map, id_map, initial_cells) {
            Value::Object(m) => Value::Object(m),
            other => other,
        };
        if let Value::Object(ref mut m) = fight {
            m.insert("actions".into(), Value::Array(actions));
        }
        fight
    }
}

fn json_i64_opt(map: &std::collections::BTreeMap<String, Value>, key: &str) -> Option<i64> {
    match map.get(key)? {
        Value::Number(n) => n.as_i64().or_else(|| n.as_u64().map(|v| v as i64)),
        _ => None,
    }
}

// (Removed) legacy Field-based map helpers. World creation now uses `WorldMap`.

fn rng_next_double_0_1(state: &mut u64) -> f64 {
    *state = state.wrapping_mul(1103515245).wrapping_add(12345);
    let r = ((*state / 65536) % 32768).wrapping_add(32768);
    (r as f64) / 65536.0
}

fn compute_start_order_for_scenario(
    scenario: &Scenario,
    id_map: &std::collections::HashMap<i32, i64>,
    rng_state: &mut i64,
) -> Vec<i64> {
    // Starting order:
    // - sort within each team by frequency desc (stable)
    // - then round-robin across teams in scenario order
    //
    // Note: the reference start-order logic does *not* consume RNG here; RNG is reserved for mapgen
    // and combat randomness. Keep `rng_state` parameter to preserve call shape.
    let _ = rng_state;
    let mut teams: Vec<Vec<(i64, i32)>> = Vec::new(); // (entity_id, frequency)
    for team in &scenario.entities {
        if team.is_empty() {
            continue;
        }
        let mut v: Vec<(i64, i32)> = team
            .iter()
            .map(|e| {
                let id = *id_map.get(&e.id).unwrap_or(&(e.id as i64));
                let freq = e.extra.get("frequency").and_then(|x| x.as_i64()).unwrap_or(0) as i32;
                (id, freq)
            })
            .collect();
        v.sort_by(|a, b| b.1.cmp(&a.1)); // stable sort in Rust
        teams.push(v);
    }
    if teams.is_empty() {
        return Vec::new();
    }
    let team_order: Vec<usize> = (0..teams.len()).collect();

    let total_entities: usize = teams.iter().map(|t| t.len()).sum();
    let mut order: Vec<i64> = Vec::with_capacity(total_entities);
    let mut cur_team_i = 0usize;
    while order.len() != total_entities {
        let t = team_order[cur_team_i];
        if !teams[t].is_empty() {
            order.push(teams[t].remove(0).0);
        }
        cur_team_i = (cur_team_i + 1) % teams.len();
    }
    order
}

fn load_weapons_db(generator_root: &Path) -> std::collections::HashMap<i64, crate::vm::WeaponDef> {
    let mut out = std::collections::HashMap::new();
    let path = generator_root.join("data/weapons.json");
    let Ok(src) = std::fs::read_to_string(&path) else {
        return out;
    };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&src) else {
        return out;
    };
    let Some(obj) = v.as_object() else {
        return out;
    };
    for (_, wv) in obj {
        let Some(wobj) = wv.as_object() else { continue };
        let item = wobj.get("item").and_then(|x| x.as_i64()).unwrap_or(0);
        if item == 0 { continue; }
        let template = wobj.get("template").and_then(|x| x.as_i64()).unwrap_or(0);
        let cost = wobj.get("cost").and_then(|x| x.as_i64()).unwrap_or(0);
        let min_range = wobj.get("min_range").and_then(|x| x.as_i64()).unwrap_or(0);
        let max_range = wobj.get("max_range").and_then(|x| x.as_i64()).unwrap_or(0);
        let launch_type_raw = wobj.get("launch_type").and_then(|x| x.as_i64()).unwrap_or(7);
        let launch_type = crate::vm::LaunchType::from_i64(launch_type_raw)
            .unwrap_or(crate::vm::LaunchType::Circle);
        let max_uses = wobj.get("max_uses").and_then(|x| x.as_i64()).unwrap_or(-1);
        let los = wobj
            .get("los")
            .and_then(|x| x.as_i64())
            .map(|v| v != 0)
            .unwrap_or(false);
        let area = wobj.get("area").and_then(|x| x.as_i64()).unwrap_or(1);
        let base_damage = wobj
            .get("effects")
            .and_then(|e| e.as_array())
            .and_then(|arr| {
                arr.iter().find_map(|eff| {
                    let o = eff.as_object()?;
                    // type==1 => DAMAGE in this dataset
                    if o.get("type")?.as_i64()? != 1 {
                        return None;
                    }
                    o.get("value1")?.as_i64()
                })
            })
            .unwrap_or(0);

        out.insert(
            item,
            crate::vm::WeaponDef {
                item: crate::vm::WeaponItemId(item),
                template: crate::vm::WeaponTemplateId(template),
                cost,
                min_range,
                max_range,
                launch_type,
                base_damage,
                los,
                area,
                max_uses,
            },
        );
    }
    out
}

fn load_chips_db(generator_root: &Path) -> std::collections::HashMap<i64, crate::vm::ChipDef> {
    let mut out = std::collections::HashMap::new();
    let path = generator_root.join("data/chips.json");
    let Ok(src) = std::fs::read_to_string(&path) else {
        return out;
    };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&src) else {
        return out;
    };
    let Some(obj) = v.as_object() else {
        return out;
    };
    for (_, cv) in obj {
        let Some(co) = cv.as_object() else { continue };
        let item = co.get("id").and_then(|x| x.as_i64()).unwrap_or(0);
        if item == 0 { continue; }
        let template = co.get("template").and_then(|x| x.as_i64()).unwrap_or(0);
        let cost = co.get("cost").and_then(|x| x.as_i64()).unwrap_or(0);
        let min_range = co.get("min_range").and_then(|x| x.as_i64()).unwrap_or(0);
        let max_range = co.get("max_range").and_then(|x| x.as_i64()).unwrap_or(0);
        let launch_type_raw = co.get("launch_type").and_then(|x| x.as_i64()).unwrap_or(7);
        let launch_type = crate::vm::LaunchType::from_i64(launch_type_raw)
            .unwrap_or(crate::vm::LaunchType::Circle);
        let area = co.get("area").and_then(|x| x.as_i64()).unwrap_or(1);
        let los = co.get("los").and_then(|x| x.as_bool()).unwrap_or(true);
        let cooldown = co.get("cooldown").and_then(|x| x.as_i64()).unwrap_or(0);
        let team_cooldown = co.get("team_cooldown").and_then(|x| x.as_bool()).unwrap_or(false);
        let initial_cooldown = co.get("initial_cooldown").and_then(|x| x.as_i64()).unwrap_or(0);
        let max_uses = co.get("max_uses").and_then(|x| x.as_i64()).unwrap_or(-1);
        let mut effects = Vec::new();
        if let Some(arr) = co.get("effects").and_then(|x| x.as_array()) {
            for ev in arr {
                let Some(eo) = ev.as_object() else { continue };
                let Some(effect_id) = crate::vm::EffectType::from_i64(
                    eo.get("id").and_then(|x| x.as_i64()).unwrap_or(0),
                ) else {
                    continue;
                };
                effects.push(crate::vm::ChipEffectDef {
                    id: effect_id,
                    value1: eo.get("value1").and_then(|x| x.as_f64()).unwrap_or(0.0),
                    value2: eo.get("value2").and_then(|x| x.as_f64()).unwrap_or(0.0),
                    turns: eo.get("turns").and_then(|x| x.as_i64()).unwrap_or(0),
                    targets: eo.get("targets").and_then(|x| x.as_i64()).unwrap_or(0),
                    modifiers: eo.get("modifiers").and_then(|x| x.as_i64()).unwrap_or(0),
                    r#type: eo.get("type").and_then(|x| x.as_i64()).unwrap_or(0),
                });
            }
        }
        out.insert(
            item,
            crate::vm::ChipDef {
                item: crate::vm::ChipItemId(item),
                template: crate::vm::ChipTemplateId(template),
                cost,
                min_range,
                max_range,
                launch_type,
                area,
                los,
                cooldown,
                team_cooldown,
                initial_cooldown,
                max_uses,
                effects,
            },
        );
    }
    out
}

fn load_summons_db(
    generator_root: &Path,
) -> std::collections::HashMap<crate::vm::SummonId, crate::vm::SummonDef> {
    let mut out = std::collections::HashMap::new();
    let path = generator_root.join("data/summons.json");
    let Ok(src) = std::fs::read_to_string(&path) else {
        return out;
    };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&src) else {
        return out;
    };
    let Some(obj) = v.as_object() else { return out };
    for (_, sv) in obj {
        let Some(so) = sv.as_object() else { continue };
        let id = so.get("id").and_then(|x| x.as_i64()).unwrap_or(0);
        if id == 0 { continue; }
        let name = so.get("name").and_then(|x| x.as_str()).unwrap_or("?").to_string();
        let chips = so.get("chips").and_then(|x| x.as_array()).map(|arr| arr.iter().filter_map(|c| c.as_i64()).collect()).unwrap_or_default();
        let chr = so.get("characteristics").and_then(|x| x.as_object());
        let get_range = |k: &str| -> (i64, i64) {
            let Some(arr) = chr.and_then(|c| c.get(k)).and_then(|v| v.as_array()) else {
                return (0, 0);
            };
            let a = arr.get(0).and_then(|x| x.as_i64()).unwrap_or(0);
            let b = arr.get(1).and_then(|x| x.as_i64()).unwrap_or(0);
            (a, b)
        };
        let sid = crate::vm::SummonId(id);
        out.insert(sid, crate::vm::SummonDef{
            id: sid,
            name,
            chips,
            life_range: get_range("life"),
            tp_range: get_range("tp"),
            mp_range: get_range("mp"),
            strength_range: get_range("strength"),
        });
    }
    out
}

fn value_to_json(v: &leekscript::vm::Value) -> Value {
    match v {
        leekscript::vm::Value::Null => Value::Null,
        leekscript::vm::Value::Bool(b) => Value::Bool(*b),
        leekscript::vm::Value::Number(n) => json!(n.as_f64()),
        leekscript::vm::Value::String(s) => Value::String(s.clone()),
        leekscript::vm::Value::Array(a) => {
            let items = a.borrow().iter().map(value_to_json).collect::<Vec<_>>();
            Value::Array(items)
        }
        leekscript::vm::Value::Map(m) => {
            let pairs = m
                .borrow()
                .iter()
                .map(|(k, val)| json!([value_to_json(k), value_to_json(val)]))
                .collect::<Vec<_>>();
            json!({ "map": pairs })
        }
        leekscript::vm::Value::Object(o) => {
            let pairs = o
                .borrow()
                .iter()
                .map(|(k, val)| json!([value_to_json(k), value_to_json(val)]))
                .collect::<Vec<_>>();
            json!({ "object": pairs })
        }
        other => json!({ "unsupported": format!("{other:?}") }),
    }
}

fn parse_scenario_from_path(path: &Path, src: &str) -> miette::Result<Scenario> {
    let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("").to_ascii_lowercase();
    if ext == "json" || ext.is_empty() {
        return serde_json::from_str::<Scenario>(src)
            .map_err(|e| miette::miette!("failed to parse scenario json: {e}"));
    }
    if ext == "toml" {
        #[cfg(feature = "toml")]
        {
            let tv: toml::Value = toml::from_str(src)
                .map_err(|e| miette::miette!("failed to parse scenario toml: {e}"))?;
            let jv = crate::util::toml_bridge::toml_to_json(&tv);
            return serde_json::from_value::<Scenario>(jv)
                .map_err(|e| miette::miette!("failed to decode scenario from toml: {e}"));
        }
        #[cfg(not(feature = "toml"))]
        {
            return Err(miette::miette!(
                "scenario `{}` is TOML but this binary was built without TOML support (enable cargo feature `toml`)",
                path.display()
            ));
        }
    }
    Err(miette::miette!(
        "unsupported scenario file extension for `{}` (expected .json or .toml)",
        path.display()
    ))
}

fn default_signature_files(base: &Path) -> Vec<PathBuf> {
    // Prefer repo-local `sig/` when running from workspace root.
    let candidates = [
        base.join("sig/std.sig.leek"),
        base.join("sig/core/stdlib.sig.const.leek"),
        base.join("sig/core/stdlib.sig.functions.leek"),
        base.join("sig/leekwars/leekwars.sig.const.leek"),
        base.join("sig/leekwars/leekwars.sig.functions.leek"),
    ];

    candidates
        .into_iter()
        .filter(|p| p.exists())
        .collect()
}
