//! Emit `leek_registry_ops.rs`: `LeekFunctions.java` + `FightFunctions.java` registry costs (numeric `method("f", …, N, …)` only; `moveToward` gets Java runtime bump).

use regex::Regex;
use std::collections::BTreeMap;
use std::path::Path;

fn main() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let out_dir_os = std::env::var_os("OUT_DIR").unwrap();
    let out_dir = Path::new(&out_dir_os);

    let leek_java = manifest.join(
        "../../leek-wars-generator/leekscript/src/main/java/leekscript/runner/LeekFunctions.java",
    );
    println!("cargo:rerun-if-changed={}", leek_java.display());

    let mut leek_costs: BTreeMap<String, u64> = BTreeMap::new();
    if let Ok(src) = std::fs::read_to_string(&leek_java) {
        let re = Regex::new(r#"method\s*\(\s*"([^"]+)"\s*,\s*"[^"]+"\s*,\s*(\d+)"#).expect("regex");
        for cap in re.captures_iter(&src) {
            let name = cap[1].to_string();
            let n: u64 = cap[2].parse().expect("ops int");
            leek_costs
                .entry(name)
                .and_modify(|e| *e = (*e).max(n))
                .or_insert(n);
        }
    }

    let fight_java = manifest
        .join("../../leek-wars-generator/src/main/java/com/leekwars/generator/FightFunctions.java");
    println!("cargo:rerun-if-changed={}", fight_java.display());

    let mut fight_costs: BTreeMap<String, u64> = BTreeMap::new();
    if let Ok(src) = std::fs::read_to_string(&fight_java) {
        let re = Regex::new(r#"method\s*\(\s*"([^"]+)"\s*,\s*"[^"]+"\s*,\s*(\d+)"#).expect("regex");
        for cap in re.captures_iter(&src) {
            let name = cap[1].to_string();
            let n: u64 = cap[2].parse().expect("ops int");
            fight_costs
                .entry(name)
                .and_modify(|e| *e = (*e).max(n))
                .or_insert(n);
        }
        if let Some(c) = fight_costs.get_mut("moveToward") {
            *c = c.saturating_add(2000);
        }
    }

    let mut rs = String::from(
        "// @generated by build.rs: LeekFunctions.java + FightFunctions.java (+ moveToward runtime ops).\n\n",
    );
    rs.push_str("pub fn leek_functions_registry_ops(name: &str) -> u64 {\n");
    rs.push_str("    match name {\n");
    for (name, n) in &leek_costs {
        if *n == 0 {
            continue;
        }
        rs.push_str("        \"");
        rs.push_str(name);
        rs.push_str("\" => ");
        rs.push_str(&n.to_string());
        rs.push_str(",\n");
    }
    rs.push_str("        _ => 0,\n");
    rs.push_str("    }\n");
    rs.push_str("}\n\n");

    rs.push_str("pub fn fight_functions_registry_ops(name: &str) -> u64 {\n");
    rs.push_str("    match name {\n");
    for (name, n) in &fight_costs {
        if *n == 0 {
            continue;
        }
        rs.push_str("        \"");
        rs.push_str(name);
        rs.push_str("\" => ");
        rs.push_str(&n.to_string());
        rs.push_str(",\n");
    }
    rs.push_str("        _ => 0,\n");
    rs.push_str("    }\n");
    rs.push_str("}\n");

    std::fs::write(out_dir.join("leek_registry_ops.rs"), rs).expect("write leek_registry_ops.rs");
}
