// Build-time metadata for the LeekScript sipha grammar.
//!
//! - Emits `cargo:rerun-if-changed` for every `src/grammar/**/*.rs` file, `Cargo.toml`, and this script.
//! - Writes `OUT_DIR/leekscript_grammar_fingerprint.rs` with [`GRAMMAR_SOURCE_FINGERPRINT`]: a stable
//!   FNV-1a 64-bit digest of sorted grammar sources plus `Cargo.toml` (so feature sets that affect
//!   `#[cfg]` in the grammar invalidate the fingerprint).
//! - With Cargo feature `compile-time-grammar`, sets `cfg(leekscript_compile_time_grammar)` for
//!   extra assertions and tests.

use std::fs;
use std::path::{Path, PathBuf};

fn fnv1a64(mut bytes: &[u8]) -> u64 {
    const OFFSET: u64 = 14695981039346656037;
    const PRIME: u64 = 1099511628211;
    let mut h = OFFSET;
    while let Some((&b, rest)) = bytes.split_first() {
        h ^= u64::from(b);
        h = h.wrapping_mul(PRIME);
        bytes = rest;
    }
    h
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for ent in entries.flatten() {
        let p = ent.path();
        if p.is_dir() {
            collect_rs_files(&p, out);
        } else if p.extension().and_then(|s| s.to_str()) == Some("rs") {
            out.push(p);
        }
    }
}

fn main() {
    println!("cargo:rustc-check-cfg=cfg(leekscript_compile_time_grammar)");

    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let grammar_root = manifest_dir.join("src/grammar");
    let cargo_toml = manifest_dir.join("Cargo.toml");
    let self_path = manifest_dir.join("build.rs");

    let mut rs_files = Vec::new();
    collect_rs_files(&grammar_root, &mut rs_files);
    rs_files.sort();

    for p in &rs_files {
        println!("cargo:rerun-if-changed={}", p.display());
    }
    println!("cargo:rerun-if-changed={}", cargo_toml.display());
    println!("cargo:rerun-if-changed={}", self_path.display());

    let mut blob: Vec<u8> = Vec::new();
    for p in &rs_files {
        let rel = p.strip_prefix(manifest_dir).unwrap_or(p);
        let rel_norm = rel.to_string_lossy().replace('\\', "/");
        blob.extend_from_slice(rel_norm.as_bytes());
        blob.push(0);
        let contents = fs::read(p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()));
        blob.extend_from_slice(&contents);
        blob.push(0);
    }
    let manifest = fs::read(&cargo_toml).unwrap_or_else(|e| panic!("read Cargo.toml: {e}"));
    blob.extend_from_slice(&manifest);

    let fp = fnv1a64(&blob);
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    let generated = format!(
        "// Generated by build.rs — do not edit.\n\
         /// Stable FNV-1a 64 digest of `src/grammar/**/*.rs` plus `Cargo.toml` (see crate `build.rs`).\n\
         pub const GRAMMAR_SOURCE_FINGERPRINT: u64 = {fp:#018x};\n"
    );
    fs::write(out_dir.join("leekscript_grammar_fingerprint.rs"), generated)
        .expect("write fingerprint");

    if std::env::var_os("CARGO_FEATURE_COMPILE_TIME_GRAMMAR").is_some() {
        println!("cargo:rustc-cfg=leekscript_compile_time_grammar");
    }
}
