//! Emit `extra_natives.rs` from `data/wars_functions.toml` and `fight_registry_ops.rs` from Java `FightFunctions.java`.

use regex::Regex;
use std::collections::BTreeMap;
use std::path::Path;

fn main() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let out_dir_os = std::env::var_os("OUT_DIR").unwrap();
    let out_dir = Path::new(&out_dir_os);

    let data_path = manifest.join("data/wars_functions.toml");
    println!("cargo:rerun-if-changed={}", data_path.display());
    let data = std::fs::read_to_string(&data_path).expect("wars_functions.toml");
    let v: toml::Value = toml::from_str(&data).expect("parse wars_functions.toml");
    let funcs = v
        .get("functions")
        .and_then(|f| f.as_array())
        .expect("functions array");
    let mut out =
        String::from("// @generated by build.rs\n\npub const EXTRA_FIGHT_NATIVES: &[&str] = &[\n");
    for f in funcs {
        let s = f.as_str().expect("function name string");
        out.push_str("    \"");
        out.push_str(s);
        out.push_str("\",\n");
    }
    out.push_str("];\n");
    std::fs::write(out_dir.join("extra_natives.rs"), out).expect("write extra_natives.rs");

    let fight_java = manifest
        .join("../../leek-wars-generator/src/main/java/com/leekwars/generator/FightFunctions.java");
    println!("cargo:rerun-if-changed={}", fight_java.display());

    let mut costs: BTreeMap<String, u64> = BTreeMap::new();
    if let Ok(src) = std::fs::read_to_string(&fight_java) {
        let re = Regex::new(r#"method\s*\(\s*"([^"]+)"\s*,\s*"[^"]+"\s*,\s*(\d+)"#).expect("regex");
        for cap in re.captures_iter(&src) {
            let name = cap[1].to_string();
            let n: u64 = cap[2].parse().expect("ops int");
            costs
                .entry(name)
                .and_modify(|e| *e = (*e).max(n))
                .or_insert(n);
        }
        if let Some(c) = costs.get_mut("moveToward") {
            *c = c.saturating_add(2000);
        }
    }

    let mut rs = String::from(
        "// @generated by build.rs from leek-wars-generator FightFunctions.java (+ moveToward runtime ops).\n\n",
    );
    rs.push_str("pub fn fight_functions_registry_ops(name: &str) -> u64 {\n");
    rs.push_str("    match name {\n");
    for (name, n) in &costs {
        rs.push_str("        \"");
        rs.push_str(name);
        rs.push_str("\" => ");
        rs.push_str(&n.to_string());
        rs.push_str(",\n");
    }
    rs.push_str("        _ => 0,\n");
    rs.push_str("    }\n");
    rs.push_str("}\n");
    std::fs::write(out_dir.join("fight_registry_ops.rs"), rs).expect("write fight_registry_ops.rs");
}
