// @generated by scripts/extract_java_vm_cases.py — do not edit by hand

mod collections {
    use super::*;

    mod testarray {
        use super::*;

        #[test]
        fn constructor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_CONSTRUCTOR);
        }

        #[test]
        fn variables() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_VARIABLES);
        }

        #[test]
        fn operator_plus() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_PLUS);
        }

        #[test]
        fn testnull_array() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTNULL_ARRAY);
        }

        #[test]
        fn misc() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_MISC);
        }

        #[test]
        fn testinfinite_array() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTINFINITE_ARRAY);
        }

        #[test]
        fn operator() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR);
        }

        #[test]
        fn testoperator_on_unknown_arrays() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTOPERATOR_ON_UNKNOWN_ARRAYS);
        }

        #[test]
        fn testout_of_bounds_exception() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTOUT_OF_BOUNDS_EXCEPTION);
        }

        #[test]
        fn testaccess_with_booleans() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTACCESS_WITH_BOOLEANS);
        }

        #[test]
        fn testaccess_negative_index() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTACCESS_NEGATIVE_INDEX);
        }

        #[test]
        fn testrange_access() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTRANGE_ACCESS);
        }

        #[test]
        fn r#in() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_IN);
        }

        #[test]
        fn not_in() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_NOT_IN);
        }

        #[test]
        fn testmethods_calls_on_unknown_array() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTMETHODS_CALLS_ON_UNKNOWN_ARRAY);
        }

        #[test]
        fn operator_plusequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_PLUSEQUALS);
        }

        #[test]
        fn operator_plusequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_PLUSEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_plusplus_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_PLUSPLUS_ON_ELEMENT);
        }

        #[test]
        fn operator_pre_plusplus_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_PRE_PLUSPLUS_ON_ELEMENT);
        }

        #[test]
        fn operator_minusminus_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_MINUSMINUS_ON_ELEMENT);
        }

        #[test]
        fn operator_pre_minusminus_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_PRE_MINUSMINUS_ON_ELEMENT);
        }

        #[test]
        fn operator_minusequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_MINUSEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_multiplyequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_MULTIPLYEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_divideequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_DIVIDEEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_backslashbackslashequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_BACKSLASHBACKSLASHEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_moduloequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_MODULOEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_multiplymultiplyequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_MULTIPLYMULTIPLYEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_orequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_OREQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_andequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_ANDEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_xorequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_XOREQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_ltltequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_LTLTEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_gtgtequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_GTGTEQUALS_ON_ELEMENT);
        }

        #[test]
        fn operator_gtgtgtequals_on_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_OPERATOR_GTGTGTEQUALS_ON_ELEMENT);
        }

        #[test]
        fn clone() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_CLONE);
        }

        #[test]
        fn json() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_JSON);
        }

        #[test]
        fn count() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_COUNT);
        }

        #[test]
        fn get() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_GET);
        }

        #[test]
        fn push() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_PUSH);
        }

        #[test]
        fn pushall() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_PUSHALL);
        }

        #[test]
        fn filter_v1_0() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_FILTER_V1_0);
        }

        #[test]
        fn filter_v1_1() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_FILTER_V1_1);
        }

        #[test]
        fn flatten() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_FLATTEN);
        }

        #[test]
        fn sort() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_SORT);
        }

        #[test]
        fn and_references() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_AND_REFERENCES);
        }

        #[test]
        fn map() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_MAP);
        }

        #[test]
        fn map_v1_0() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_MAP_V1_0);
        }

        #[test]
        fn map_v1_1() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_MAP_V1_1);
        }

        #[test]
        fn foldleft() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_FOLDLEFT);
        }

        #[test]
        fn foldright() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_FOLDRIGHT);
        }

        #[test]
        fn partition() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_PARTITION);
        }

        #[test]
        fn concat() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_CONCAT);
        }

        #[test]
        fn iter() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_ITER);
        }

        #[test]
        fn sort_2() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_SORT_2);
        }

        #[test]
        fn remove() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_REMOVE);
        }

        #[test]
        fn removeall() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_REMOVEALL);
        }

        #[test]
        fn count_2() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_COUNT_2);
        }

        #[test]
        fn join() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_JOIN);
        }

        #[test]
        fn insert() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_INSERT);
        }

        #[test]
        fn unshift() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_UNSHIFT);
        }

        #[test]
        fn shift() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_SHIFT);
        }

        #[test]
        fn pop() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_POP);
        }

        #[test]
        fn removeelement() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_REMOVEELEMENT);
        }

        #[test]
        fn sort_3() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_SORT_3);
        }

        #[test]
        fn search() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_SEARCH);
        }

        #[test]
        fn inarray() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_INARRAY);
        }

        #[test]
        fn reverse() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_REVERSE);
        }

        #[test]
        fn arraymin() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_ARRAYMIN);
        }

        #[test]
        fn arraymax() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_ARRAYMAX);
        }

        #[test]
        fn sum() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_SUM);
        }

        #[test]
        fn average() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_AVERAGE);
        }

        #[test]
        fn fill() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_FILL);
        }

        #[test]
        fn isempty() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_ISEMPTY);
        }

        #[test]
        fn subarray_divide_arrayslice() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_SUBARRAY_DIVIDE_ARRAYSLICE);
        }

        #[test]
        fn assocreverse() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_ASSOCREVERSE);
        }

        #[test]
        fn some() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_SOME);
        }

        #[test]
        fn find() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_FIND);
        }

        #[test]
        fn every() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_EVERY);
        }

        #[test]
        fn random() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_RANDOM);
        }

        #[test]
        fn frequencies() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_FREQUENCIES);
        }

        #[test]
        fn chunk() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_CHUNK);
        }

        #[test]
        fn unique() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_UNIQUE);
        }

        #[test]
        fn types() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_TYPES);
        }

        #[test]
        fn testextends_array_class() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTEXTENDS_ARRAY_CLASS);
        }

        #[test]
        fn arraytoset() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_ARRAYTOSET);
        }

        #[test]
        fn access_real_to_integer_cast() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY__TESTARRAY_ACCESS_REAL_TO_INTEGER_CAST);
        }

    }

    mod testarraystress {
        use super::*;

        #[test]
        #[ignore = "Java VM parity stress — TestArrayStress.java — run with --ignored"]
        fn run() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY_STRESS__RUN);
        }

    }

    mod testmap {
        use super::*;

        #[test]
        fn testconstructor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTCONSTRUCTOR);
        }

        #[test]
        fn testmapto_bool() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPTO_BOOL);
        }

        #[test]
        fn testarray_of_maps() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTARRAY_OF_MAPS);
        }

        #[test]
        fn testinfinite_maps() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTINFINITE_MAPS);
        }

        #[test]
        fn duplicated_key() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_DUPLICATED_KEY);
        }

        #[test]
        fn operator_equalsequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_OPERATOR_EQUALSEQUALS);
        }

        #[test]
        fn operator() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_OPERATOR);
        }

        #[test]
        fn operator_leftminusvalue() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_OPERATOR_LEFTMINUSVALUE);
        }

        #[test]
        fn testoperators_on_map_element() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTOPERATORS_ON_MAP_ELEMENT);
        }

        #[test]
        fn operator_plus() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_OPERATOR_PLUS);
        }

        #[test]
        fn operator_plusequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_OPERATOR_PLUSEQUALS);
        }

        #[test]
        fn instanceof() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_INSTANCEOF);
        }

        #[test]
        fn clone() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_CLONE);
        }

        #[test]
        fn json() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_JSON);
        }

        #[test]
        fn iteration() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_ITERATION);
        }

        #[test]
        fn isempty() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_ISEMPTY);
        }

        #[test]
        fn clear() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_CLEAR);
        }

        #[test]
        fn get() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_GET);
        }

        #[test]
        fn put() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_PUT);
        }

        #[test]
        fn keys() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_KEYS);
        }

        #[test]
        fn values() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_VALUES);
        }

        #[test]
        fn testmapmap() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPMAP);
        }

        #[test]
        fn testmapremove() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPREMOVE);
        }

        #[test]
        fn removeall() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_REMOVEALL);
        }

        #[test]
        fn replace() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_REPLACE);
        }

        #[test]
        fn replaceall() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_REPLACEALL);
        }

        #[test]
        fn fill() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_FILL);
        }

        #[test]
        fn testassocsort_legacy() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTASSOCSORT_LEGACY);
        }

        #[test]
        fn testkeysort_legacy() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTKEYSORT_LEGACY);
        }

        #[test]
        fn testmapsearch() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPSEARCH);
        }

        #[test]
        fn testmapcontains() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPCONTAINS);
        }

        #[test]
        fn testmapcontainskey() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPCONTAINSKEY);
        }

        #[test]
        fn r#in() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_IN);
        }

        #[test]
        fn not_in() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_NOT_IN);
        }

        #[test]
        fn testmapmin() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPMIN);
        }

        #[test]
        fn testmapmax() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPMAX);
        }

        #[test]
        fn testmapsum() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPSUM);
        }

        #[test]
        fn testmapaverage() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAPAVERAGE);
        }

        #[test]
        fn testassocreverse() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTASSOCREVERSE);
        }

        #[test]
        fn some() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_SOME);
        }

        #[test]
        fn every() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_EVERY);
        }

        #[test]
        fn fold() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_FOLD);
        }

        #[test]
        fn filter() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_FILTER);
        }

        #[test]
        fn merge() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP__TESTMAP_MERGE);
        }

    }

    mod testmapstress {
        use super::*;

        #[test]
        #[ignore = "Java VM parity stress — TestMapStress.java — run with --ignored"]
        fn run() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP_STRESS__RUN);
        }

    }

    mod testobject {
        use super::*;

        #[test]
        fn run() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OBJECT__RUN);
        }

        #[test]
        fn setinteger() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OBJECT__SETINTEGER);
        }

        #[test]
        fn testfieldconversion() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OBJECT__TESTFIELDCONVERSION);
        }

    }

    mod testobjectstress {
        use super::*;

        #[test]
        #[ignore = "Java VM parity stress — TestObjectStress.java — run with --ignored"]
        fn run() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OBJECT_STRESS__RUN);
        }

    }

    mod testset {
        use super::*;

        #[test]
        fn constructor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_CONSTRUCTOR);
        }

        #[test]
        fn typing() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_TYPING);
        }

        #[test]
        fn operator_equalsequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_OPERATOR_EQUALSEQUALS);
        }

        #[test]
        fn operator_not() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_OPERATOR_NOT);
        }

        #[test]
        fn setput() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_SETPUT);
        }

        #[test]
        fn setremove() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_SETREMOVE);
        }

        #[test]
        fn setclear() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_SETCLEAR);
        }

        #[test]
        fn setcontains() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_SETCONTAINS);
        }

        #[test]
        fn r#in() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_IN);
        }

        #[test]
        fn not_in() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_NOT_IN);
        }

        #[test]
        fn setsize() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_SETSIZE);
        }

        #[test]
        fn setisempty() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_SETISEMPTY);
        }

        #[test]
        fn setsubsetof() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_SETSUBSETOF);
        }

        #[test]
        fn iteration() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_ITERATION);
        }

        #[test]
        fn union() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_UNION);
        }

        #[test]
        fn intersection() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_INTERSECTION);
        }

        #[test]
        fn difference() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_DIFFERENCE);
        }

        #[test]
        fn disjunction() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_DISJUNCTION);
        }

        #[test]
        fn toarray() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_TOARRAY);
        }

        #[test]
        fn clone() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SET__TESTSET_CLONE);
        }

    }

}

mod control_flow {
    use super::*;

    mod testif {
        use super::*;

        #[test]
        fn testinit() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_IF__TESTINIT);
        }

        #[test]
        fn testconditions_with_other_types() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_IF__TESTCONDITIONS_WITH_OTHER_TYPES);
        }

        #[test]
        fn testdifferent_branch_types() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_IF__TESTDIFFERENT_BRANCH_TYPES);
        }

        #[test]
        fn testternary_conditions() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_IF__TESTTERNARY_CONDITIONS);
        }

        #[test]
        fn testinvalid_ternary_syntax() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_IF__TESTINVALID_TERNARY_SYNTAX);
        }

    }

    mod testinterval {
        use super::*;

        #[test]
        fn constructor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_CONSTRUCTOR);
        }

        #[test]
        fn intervalmin() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALMIN);
        }

        #[test]
        fn intervalmax() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALMAX);
        }

        #[test]
        fn intervalisempty() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALISEMPTY);
        }

        #[test]
        fn as_boolean() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_AS_BOOLEAN);
        }

        #[test]
        fn intervalisbounded() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALISBOUNDED);
        }

        #[test]
        fn intervalisleftbounded() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALISLEFTBOUNDED);
        }

        #[test]
        fn intervalisrightbounded() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALISRIGHTBOUNDED);
        }

        #[test]
        fn r#in() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_IN);
        }

        #[test]
        fn intervalcontains() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALCONTAINS);
        }

        #[test]
        fn typing() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_TYPING);
        }

        #[test]
        fn intervalaverage() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALAVERAGE);
        }

        #[test]
        fn intervalintersection() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALINTERSECTION);
        }

        #[test]
        fn intervalcombine() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALCOMBINE);
        }

        #[test]
        fn intervaltoarray() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALTOARRAY);
        }

        #[test]
        fn intervaltoarray_2() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALTOARRAY_2);
        }

        #[test]
        fn intervaltoarray_3() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALTOARRAY_3);
        }

        #[test]
        fn intervaltoset() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALTOSET);
        }

        #[test]
        fn intervaltoset_2() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALTOSET_2);
        }

        #[test]
        fn intervaltoset_3() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_INTERVALTOSET_3);
        }

        #[test]
        fn startendstep() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_STARTENDSTEP);
        }

        #[test]
        fn iteration() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL__TESTINTERVAL_ITERATION);
        }

    }

    mod testloops {
        use super::*;

        #[test]
        fn testwhile_loops() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTWHILE_LOOPS);
        }

        #[test]
        fn testdouble_while_loops() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTDOUBLE_WHILE_LOOPS);
        }

        #[test]
        fn testdo_while() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTDO_WHILE);
        }

        #[test]
        fn testdo_while_without_semicolon() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTDO_WHILE_WITHOUT_SEMICOLON);
        }

        #[test]
        fn testfor_loops() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOR_LOOPS);
        }

        #[test]
        fn testfor_variable_defined_before_the_loop() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOR_VARIABLE_DEFINED_BEFORE_THE_LOOP);
        }

        #[test]
        fn testfor_whitout_braces() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOR_WHITOUT_BRACES);
        }

        #[test]
        fn testfor_loops_with_returns() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOR_LOOPS_WITH_RETURNS);
        }

        #[test]
        fn testnested_for_loops() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTNESTED_FOR_LOOPS);
        }

        #[test]
        fn testmix_for_and_while_loops() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTMIX_FOR_AND_WHILE_LOOPS);
        }

        #[test]
        fn testempty_containers() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTEMPTY_CONTAINERS);
        }

        #[test]
        fn testnormal_containers() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTNORMAL_CONTAINERS);
        }

        #[test]
        fn testforeach_minus_no_braces() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOREACH_MINUS_NO_BRACES);
        }

        #[test]
        fn testforeach_minus_double() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOREACH_MINUS_DOUBLE);
        }

        #[test]
        fn testforeach_minus_references() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOREACH_MINUS_REFERENCES);
        }

        #[test]
        fn testforeach_minus_captures() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOREACH_MINUS_CAPTURES);
        }

        #[test]
        fn testforeach_minus_return() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOREACH_MINUS_RETURN);
        }

        #[test]
        fn testforeach_minus_argument() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOREACH_MINUS_ARGUMENT);
        }

        #[test]
        fn testforeach_minus_variable_used_in_container() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS__TESTFOREACH_MINUS_VARIABLE_USED_IN_CONTAINER);
        }

    }

    mod testswitch {
        use super::*;

        #[test]
        fn testbasic_switch() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTBASIC_SWITCH);
        }

        #[test]
        fn with_default() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_DEFAULT);
        }

        #[test]
        fn with_break() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_BREAK);
        }

        #[test]
        fn with_break_and_default() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_BREAK_AND_DEFAULT);
        }

        #[test]
        fn testmultiple_case_values() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTMULTIPLE_CASE_VALUES);
        }

        #[test]
        fn with_strings() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_STRINGS);
        }

        #[test]
        fn with_expressions() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_EXPRESSIONS);
        }

        #[test]
        fn with_multiple_instructions_in_case() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_MULTIPLE_INSTRUCTIONS_IN_CASE);
        }

        #[test]
        fn in_function() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_IN_FUNCTION);
        }

        #[test]
        fn with_null() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_NULL);
        }

        #[test]
        fn with_boolean() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_BOOLEAN);
        }

        #[test]
        fn testnested_switch() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTNESTED_SWITCH);
        }

        #[test]
        fn in_loop() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_IN_LOOP);
        }

        #[test]
        fn with_if_inside_case() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_IF_INSIDE_CASE);
        }

        #[test]
        fn with_for_inside_case() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_FOR_INSIDE_CASE);
        }

        #[test]
        fn with_while_inside_case() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_WITH_WHILE_INSIDE_CASE);
        }

        #[test]
        fn case_with_if_and_no_break() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTSWITCH_CASE_WITH_IF_AND_NO_BREAK);
        }

        #[test]
        fn testempty_switch() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH__TESTEMPTY_SWITCH);
        }

    }

}

mod io {
    use super::*;

    mod testfiles {
        use super::*;

        #[test]
        fn run() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FILES__RUN);
        }

    }

    mod testjson {
        use super::*;

        #[test]
        fn testjsonencode() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_JSON__TESTJSONENCODE);
        }

        #[test]
        fn testjsondecode() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_JSON__TESTJSONDECODE);
        }

        #[test]
        fn testcombinations() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_JSON__TESTCOMBINATIONS);
        }

    }

    mod testsystem {
        use super::*;

        #[test]
        fn run() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_SYSTEM__RUN);
        }

    }

}

mod language {
    use super::*;

    mod testclass {
        use super::*;

        #[test]
        fn toboolean() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_CLASS__TESTCLASS_TOBOOLEAN);
        }

        #[test]
        fn and_variable() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_CLASS__TESTCLASS_AND_VARIABLE);
        }

        #[test]
        fn name() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_CLASS__TESTCLASS_NAME);
        }

        #[test]
        fn testmethod_call_with_nullable_argument() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_CLASS__TESTMETHOD_CALL_WITH_NULLABLE_ARGUMENT);
        }

        #[test]
        fn testnonminusexistent_field_access() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_CLASS__TESTNONMINUSEXISTENT_FIELD_ACCESS);
        }

    }

    mod testcomments {
        use super::*;

        #[test]
        fn run() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_COMMENTS__RUN);
        }

    }

    mod testfunction {
        use super::*;

        #[test]
        fn testfunction() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTFUNCTION);
        }

        #[test]
        fn toboolean() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTFUNCTION_TOBOOLEAN);
        }

        #[test]
        fn testfunctions_divide_lambdas() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTFUNCTIONS_DIVIDE_LAMBDAS);
        }

        #[test]
        fn testrecursive() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTRECURSIVE);
        }

        #[test]
        fn testredefinition() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTREDEFINITION);
        }

        #[test]
        fn testsystem_function_as_argument() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTSYSTEM_FUNCTION_AS_ARGUMENT);
        }

        #[test]
        fn testsingle_null_argument() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTSINGLE_NULL_ARGUMENT);
        }

        #[test]
        fn testcapture_argument() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTCAPTURE_ARGUMENT);
        }

        #[test]
        fn testcapture_loop_variable() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTCAPTURE_LOOP_VARIABLE);
        }

        #[test]
        fn with_references() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTFUNCTION_WITH_REFERENCES);
        }

        #[test]
        fn testreturn_reference() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTRETURN_REFERENCE);
        }

        #[test]
        fn testmisc() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTMISC);
        }

        #[test]
        fn testmodify_argument() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTMODIFY_ARGUMENT);
        }

        #[test]
        fn testknapsack_variants() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTKNAPSACK_VARIANTS);
        }

        #[test]
        fn teststrings_leek_variations() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTSTRINGS_LEEK_VARIATIONS);
        }

        #[test]
        fn testsystem_function_typing() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTSYSTEM_FUNCTION_TYPING);
        }

        #[test]
        fn testwrong_number_of_arguments() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTWRONG_NUMBER_OF_ARGUMENTS);
        }

        #[test]
        fn testtypes() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTTYPES);
        }

        #[test]
        fn testconditional_return() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTCONDITIONAL_RETURN);
        }

        #[test]
        fn testreturn_type_warnings() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTRETURN_TYPE_WARNINGS);
        }

        #[test]
        fn testdefault_parameters() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION__TESTDEFAULT_PARAMETERS);
        }

    }

    mod testglobals {
        use super::*;

        #[test]
        fn testglobals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GLOBALS__TESTGLOBALS);
        }

        #[test]
        fn operators() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GLOBALS__TESTGLOBALS_OPERATORS);
        }

        #[test]
        fn testtypes() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GLOBALS__TESTTYPES);
        }

    }

    mod testnarrowing {
        use super::*;

        #[test]
        fn testbasic_null_check_if() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTBASIC_NULL_CHECK_IF);
        }

        #[test]
        fn testequality_null_check_if() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTEQUALITY_NULL_CHECK_IF);
        }

        #[test]
        fn testtruthy_check_if() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTTRUTHY_CHECK_IF);
        }

        #[test]
        fn testcase_1_andand_divide_oror_operators() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTCASE_1_ANDAND_DIVIDE_OROR_OPERATORS);
        }

        #[test]
        fn testcase_2_early_return_narrowing() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTCASE_2_EARLY_RETURN_NARROWING);
        }

        #[test]
        fn testcase_3_while_loop_narrowing() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTCASE_3_WHILE_LOOP_NARROWING);
        }

        #[test]
        fn testcase_4_instanceof_narrowing() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTCASE_4_INSTANCEOF_NARROWING);
        }

        #[test]
        fn testcase_5_assignment_in_condition() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTCASE_5_ASSIGNMENT_IN_CONDITION);
        }

        #[test]
        fn testnegation_not() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTNEGATION_NOT);
        }

        #[test]
        fn testearly_return_in_function_with_parameter() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTEARLY_RETURN_IN_FUNCTION_WITH_PARAMETER);
        }

        #[test]
        fn testelseminusif_chains() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTELSEMINUSIF_CHAINS);
        }

        #[test]
        fn testswitch_narrowing() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTSWITCH_NARROWING);
        }

        #[test]
        fn testclass_field_narrowing() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTCLASS_FIELD_NARROWING);
        }

        #[test]
        fn testinstanceof_narrowing_with_compound_types() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTINSTANCEOF_NARROWING_WITH_COMPOUND_TYPES);
        }

        #[test]
        fn testinstanceof_narrowing_with_property_access() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTINSTANCEOF_NARROWING_WITH_PROPERTY_ACCESS);
        }

        #[test]
        fn testinstanceof_primitive_narrowing_in_else_branch() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTINSTANCEOF_PRIMITIVE_NARROWING_IN_ELSE_BRANCH);
        }

        #[test]
        fn testinstanceof_narrowing_wrapper_box_variable() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTINSTANCEOF_NARROWING_WRAPPER_BOX_VARIABLE);
        }

        #[test]
        fn testas_cast_with_instanceof_narrowing_in_and() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTAS_CAST_WITH_INSTANCEOF_NARROWING_IN_AND);
        }

        #[test]
        fn testcompound_type_with_map_and_integer_instanceof() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTCOMPOUND_TYPE_WITH_MAP_AND_INTEGER_INSTANCEOF);
        }

        #[test]
        fn testglobal_variable_assignment_inside_null_check() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTGLOBAL_VARIABLE_ASSIGNMENT_INSIDE_NULL_CHECK);
        }

        #[test]
        fn testinstanceof_narrowing_nullable_property_access() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING__TESTINSTANCEOF_NARROWING_NULLABLE_PROPERTY_ACCESS);
        }

    }

    mod testreference {
        use super::*;

        #[test]
        fn run() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_REFERENCE__RUN);
        }

    }

}

mod misc {
    use super::*;

    mod testedgecases {
        use super::*;

        #[test]
        fn testdeep_recursion_with_temporary_arrays() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTDEEP_RECURSION_WITH_TEMPORARY_ARRAYS);
        }

        #[test]
        fn testminimaxminuslike_patterns() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTMINIMAXMINUSLIKE_PATTERNS);
        }

        #[test]
        fn testdeeply_nested_structures() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTDEEPLY_NESTED_STRUCTURES);
        }

        #[test]
        fn testnull_reference_edge_cases() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTNULL_REFERENCE_EDGE_CASES);
        }

        #[test]
        fn testoperations_limit_edge_cases() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTOPERATIONS_LIMIT_EDGE_CASES);
        }

        #[test]
        fn testram_limit_edge_cases() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTRAM_LIMIT_EDGE_CASES);
        }

        #[test]
        fn testgc_scenarios_minus_temporary_object_cleanup() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTGC_SCENARIOS_MINUS_TEMPORARY_OBJECT_CLEANUP);
        }

        #[test]
        fn testcomplex_data_structure_patterns() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTCOMPLEX_DATA_STRUCTURE_PATTERNS);
        }

        #[test]
        fn testclosure_memory_edge_cases() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTCLOSURE_MEMORY_EDGE_CASES);
        }

        #[test]
        fn testtype_coercion_edge_cases() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTTYPE_COERCION_EDGE_CASES);
        }

        #[test]
        fn testboundary_values() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTBOUNDARY_VALUES);
        }

        #[test]
        fn testcombined_stress_test() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTCOMBINED_STRESS_TEST);
        }

        #[test]
        fn testtournamentminuslike_stress_scenarios() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTTOURNAMENTMINUSLIKE_STRESS_SCENARIOS);
        }

        #[test]
        fn testvalue_conversions() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTVALUE_CONVERSIONS);
        }

        #[test]
        fn testcomplex_assignments() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTCOMPLEX_ASSIGNMENTS);
        }

        #[test]
        fn testtype_inference_in_functions() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTTYPE_INFERENCE_IN_FUNCTIONS);
        }

        #[test]
        fn testoperator_assignment_edge_cases() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTOPERATOR_ASSIGNMENT_EDGE_CASES);
        }

        #[test]
        fn testaccess_pattern_edge_cases() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTACCESS_PATTERN_EDGE_CASES);
        }

        #[test]
        fn testmap_array_access_type_mismatch() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTMAP_ARRAY_ACCESS_TYPE_MISMATCH);
        }

        #[test]
        fn testreference_vs_copy_semantics() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES__TESTREFERENCE_VS_COPY_SEMANTICS);
        }

    }

    mod testeuler {
        use super::*;

        #[test]
        fn run() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_EULER__RUN);
        }

    }

    mod testgeneral {
        use super::*;

        #[test]
        fn testnull() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTNULL);
        }

        #[test]
        fn testcolor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTCOLOR);
        }

        #[test]
        fn testglobals_with_keywords() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTGLOBALS_WITH_KEYWORDS);
        }

        #[test]
        fn testtype_changes() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTTYPE_CHANGES);
        }

        #[test]
        fn testassignments() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTASSIGNMENTS);
        }

        #[test]
        fn testassignments_with_plusequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTASSIGNMENTS_WITH_PLUSEQUALS);
        }

        #[test]
        fn testfile() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTFILE);
        }

        #[test]
        fn testnumber() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTNUMBER);
        }

        #[test]
        fn testvariables_with_accents() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTVARIABLES_WITH_ACCENTS);
        }

        #[test]
        fn testvariables_and_types() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTVARIABLES_AND_TYPES);
        }

        #[test]
        fn testunusedvariable() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL__TESTUNUSEDVARIABLE);
        }

    }

}

mod operators {
    use super::*;

    mod testoperations {
        use super::*;

        #[test]
        fn testoperators() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATIONS__TESTOPERATORS);
        }

        #[test]
        fn testconditions() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATIONS__TESTCONDITIONS);
        }

        #[test]
        fn testboolean_operators() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATIONS__TESTBOOLEAN_OPERATORS);
        }

    }

    mod testoperators {
        use super::*;

        #[test]
        fn testoperator_equalsequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATORS__TESTOPERATOR_EQUALSEQUALS);
        }

        #[test]
        fn testother_operators() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATORS__TESTOTHER_OPERATORS);
        }

        #[test]
        fn testoperator_equalsequalsequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATORS__TESTOPERATOR_EQUALSEQUALSEQUALS);
        }

        #[test]
        fn testoperator_plus() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATORS__TESTOPERATOR_PLUS);
        }

        #[test]
        fn testcomparison_always_false() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATORS__TESTCOMPARISON_ALWAYS_FALSE);
        }

        #[test]
        fn testcomparison_always_true() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATORS__TESTCOMPARISON_ALWAYS_TRUE);
        }

        #[test]
        fn testunknown_operator() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATORS__TESTUNKNOWN_OPERATOR);
        }

    }

}

mod primitives {
    use super::*;

    mod testboolean {
        use super::*;

        #[test]
        fn testboolean() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_BOOLEAN__TESTBOOLEAN);
        }

        #[test]
        fn operator_not() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_BOOLEAN__TESTBOOLEAN_OPERATOR_NOT);
        }

        #[test]
        fn operator_xor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_BOOLEAN__TESTBOOLEAN_OPERATOR_XOR);
        }

    }

    mod testnumber {
        use super::*;

        #[test]
        fn testbasicnumbers() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTBASICNUMBERS);
        }

        #[test]
        fn testspecialcharacters() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTSPECIALCHARACTERS);
        }

        #[test]
        fn testclass() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTCLASS);
        }

        #[test]
        fn testlexicalerrors() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTLEXICALERRORS);
        }

        #[test]
        fn testbasicoperations() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTBASICOPERATIONS);
        }

        #[test]
        fn testhexadecimalrepresentation() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTHEXADECIMALREPRESENTATION);
        }

        #[test]
        fn testbinaryrepresentation() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTBINARYREPRESENTATION);
        }

        #[test]
        fn testunderscoredelimiters() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTUNDERSCOREDELIMITERS);
        }

        #[test]
        fn testnullnotconsideredaszero() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTNULLNOTCONSIDEREDASZERO);
        }

        #[test]
        fn testnumberswithvariables() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTNUMBERSWITHVARIABLES);
        }

        #[test]
        fn testmultipleoperations() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTMULTIPLEOPERATIONS);
        }

        #[test]
        fn testconstructor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTCONSTRUCTOR);
        }

        #[test]
        fn testconstants() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTCONSTANTS);
        }

        #[test]
        fn testconstantsinclass() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTCONSTANTSINCLASS);
        }

        #[test]
        fn testoperatorunaryminus() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORUNARYMINUS);
        }

        #[test]
        fn testoperatorunarynot() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORUNARYNOT);
        }

        #[test]
        fn testoperatorunarybitwisenot() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORUNARYBITWISENOT);
        }

        #[test]
        fn testoperatorprefixincrement() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORPREFIXINCREMENT);
        }

        #[test]
        fn testoperatorprefixdecrement() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORPREFIXDECREMENT);
        }

        #[test]
        fn testoperatorpostfixincrement() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORPOSTFIXINCREMENT);
        }

        #[test]
        fn testoperatorpostfixdecrement() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORPOSTFIXDECREMENT);
        }

        #[test]
        fn testoperatorequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATOREQUALS);
        }

        #[test]
        fn testoperatorplus() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORPLUS);
        }

        #[test]
        fn testoperatorplusequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORPLUSEQUALS);
        }

        #[test]
        fn testoperatorminus() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORMINUS);
        }

        #[test]
        fn testoperatorminusequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORMINUSEQUALS);
        }

        #[test]
        fn testoperatormultiply() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORMULTIPLY);
        }

        #[test]
        fn testoperatormultiplyequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORMULTIPLYEQUALS);
        }

        #[test]
        fn testoperatorpower() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORPOWER);
        }

        #[test]
        fn testoperatorpowerequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORPOWEREQUALS);
        }

        #[test]
        fn testoperatormodulo() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORMODULO);
        }

        #[test]
        fn testoperatormoduloequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORMODULOEQUALS);
        }

        #[test]
        fn testoperatordivide() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORDIVIDE);
        }

        #[test]
        fn testoperatordivideequals() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORDIVIDEEQUALS);
        }

        #[test]
        fn testoperatorlessthan() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORLESSTHAN);
        }

        #[test]
        fn testoperatorlessthanorequal() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORLESSTHANOREQUAL);
        }

        #[test]
        fn testoperatorgreaterthan() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORGREATERTHAN);
        }

        #[test]
        fn testoperatorgreaterthanorequal() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORGREATERTHANOREQUAL);
        }

        #[test]
        fn testoperatorbitwiseand() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORBITWISEAND);
        }

        #[test]
        fn testoperatorbitwiseor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORBITWISEOR);
        }

        #[test]
        fn testoperatorbitwisexor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORBITWISEXOR);
        }

        #[test]
        fn testoperatorleftshift() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORLEFTSHIFT);
        }

        #[test]
        fn testoperatorrightshift() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORRIGHTSHIFT);
        }

        #[test]
        fn testoperatorunsignedrightshift() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTOPERATORUNSIGNEDRIGHTSHIFT);
        }

        #[test]
        fn testnotastatementerrors() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTNOTASTATEMENTERRORS);
        }

        #[test]
        fn testabs() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTABS);
        }

        #[test]
        fn testexp() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTEXP);
        }

        #[test]
        fn testfloor() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTFLOOR);
        }

        #[test]
        fn testround() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTROUND);
        }

        #[test]
        fn testceil() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTCEIL);
        }

        #[test]
        fn testmax() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTMAX);
        }

        #[test]
        fn testmin() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTMIN);
        }

        #[test]
        fn testcos() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTCOS);
        }

        #[test]
        fn testacos() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTACOS);
        }

        #[test]
        fn testsin() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTSIN);
        }

        #[test]
        fn testtan() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTTAN);
        }

        #[test]
        fn testasin() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTASIN);
        }

        #[test]
        fn testatan() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTATAN);
        }

        #[test]
        fn testatan2() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTATAN2);
        }

        #[test]
        fn testcbrt() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTCBRT);
        }

        #[test]
        fn testhypot() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTHYPOT);
        }

        #[test]
        fn testsignum() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTSIGNUM);
        }

        #[test]
        fn testsqrt() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTSQRT);
        }

        #[test]
        fn testtodegrees() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTTODEGREES);
        }

        #[test]
        fn testtoradians() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTTORADIANS);
        }

        #[test]
        fn testlog() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTLOG);
        }

        #[test]
        fn testlog10() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTLOG10);
        }

        #[test]
        fn testpow() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTPOW);
        }

        #[test]
        fn testrand() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTRAND);
        }

        #[test]
        fn testbitcount() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTBITCOUNT);
        }

        #[test]
        fn testtrailingzeros() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTTRAILINGZEROS);
        }

        #[test]
        fn testleadingzeros() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTLEADINGZEROS);
        }

        #[test]
        fn testbitreverse() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTBITREVERSE);
        }

        #[test]
        fn testbytereverse() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTBYTEREVERSE);
        }

        #[test]
        fn testbinstring() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTBINSTRING);
        }

        #[test]
        fn testhexstring() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTHEXSTRING);
        }

        #[test]
        fn testrotateleft() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTROTATELEFT);
        }

        #[test]
        fn testrotateright() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTROTATERIGHT);
        }

        #[test]
        fn testrealbits() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTREALBITS);
        }

        #[test]
        fn testbitstoreal() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTBITSTOREAL);
        }

        #[test]
        fn testisfinite() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTISFINITE);
        }

        #[test]
        fn testisinfinite() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTISINFINITE);
        }

        #[test]
        fn testisnan() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTISNAN);
        }

        #[test]
        fn testispermutation() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER__TESTISPERMUTATION);
        }

    }

    mod teststring {
        use super::*;

        #[test]
        fn testoperator_plus() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTOPERATOR_PLUS);
        }

        #[test]
        fn charat() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_CHARAT);
        }

        #[test]
        fn length() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_LENGTH);
        }

        #[test]
        fn substring() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_SUBSTRING);
        }

        #[test]
        fn replace() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_REPLACE);
        }

        #[test]
        fn indexof() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_INDEXOF);
        }

        #[test]
        fn split() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_SPLIT);
        }

        #[test]
        fn tolower() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_TOLOWER);
        }

        #[test]
        fn toupper() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_TOUPPER);
        }

        #[test]
        fn startswith() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_STARTSWITH);
        }

        #[test]
        fn endswith() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_ENDSWITH);
        }

        #[test]
        fn contains() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_CONTAINS);
        }

        #[test]
        fn string() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_STRING);
        }

        #[test]
        fn codepointat() {
            run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING__TESTSTRING_CODEPOINTAT);
        }

    }

}

