// @generated by scripts/extract_java_vm_cases.py — do not edit by hand

#[test]
#[ignore = "Java VM parity — TestArray.java — run with --ignored"]
fn java_vm_export_test_array() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY);
}

#[test]
#[ignore = "Java VM parity — TestArrayStress.java — run with --ignored"]
fn java_vm_export_test_array_stress() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_ARRAY_STRESS);
}

#[test]
#[ignore = "Java VM parity — TestBoolean.java — run with --ignored"]
fn java_vm_export_test_boolean() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_BOOLEAN);
}

#[test]
#[ignore = "Java VM parity — TestClass.java — run with --ignored"]
fn java_vm_export_test_class() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_CLASS);
}

#[test]
#[ignore = "Java VM parity — TestComments.java — run with --ignored"]
fn java_vm_export_test_comments() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_COMMENTS);
}

#[test]
#[ignore = "Java VM parity — TestEdgeCases.java — run with --ignored"]
fn java_vm_export_test_edge_cases() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_EDGE_CASES);
}

#[test]
#[ignore = "Java VM parity — TestEuler.java — run with --ignored"]
fn java_vm_export_test_euler() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_EULER);
}

#[test]
#[ignore = "Java VM parity — TestFiles.java — run with --ignored"]
fn java_vm_export_test_files() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_FILES);
}

#[test]
#[ignore = "Java VM parity — TestFunction.java — run with --ignored"]
fn java_vm_export_test_function() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_FUNCTION);
}

#[test]
#[ignore = "Java VM parity — TestGeneral.java — run with --ignored"]
fn java_vm_export_test_general() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_GENERAL);
}

#[test]
#[ignore = "Java VM parity — TestGlobals.java — run with --ignored"]
fn java_vm_export_test_globals() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_GLOBALS);
}

#[test]
#[ignore = "Java VM parity — TestIf.java — run with --ignored"]
fn java_vm_export_test_if() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_IF);
}

#[test]
#[ignore = "Java VM parity — TestInterval.java — run with --ignored"]
fn java_vm_export_test_interval() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_INTERVAL);
}

#[test]
#[ignore = "Java VM parity — TestJSON.java — run with --ignored"]
fn java_vm_export_test_json() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_JSON);
}

#[test]
#[ignore = "Java VM parity — TestLoops.java — run with --ignored"]
fn java_vm_export_test_loops() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_LOOPS);
}

#[test]
#[ignore = "Java VM parity — TestMap.java — run with --ignored"]
fn java_vm_export_test_map() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP);
}

#[test]
#[ignore = "Java VM parity — TestMapStress.java — run with --ignored"]
fn java_vm_export_test_map_stress() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_MAP_STRESS);
}

#[test]
#[ignore = "Java VM parity — TestNarrowing.java — run with --ignored"]
fn java_vm_export_test_narrowing() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_NARROWING);
}

#[test]
#[ignore = "Java VM parity — TestNumber.java — run with --ignored"]
fn java_vm_export_test_number() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_NUMBER);
}

#[test]
#[ignore = "Java VM parity — TestObject.java — run with --ignored"]
fn java_vm_export_test_object() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_OBJECT);
}

#[test]
#[ignore = "Java VM parity — TestObjectStress.java — run with --ignored"]
fn java_vm_export_test_object_stress() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_OBJECT_STRESS);
}

#[test]
#[ignore = "Java VM parity — TestOperations.java — run with --ignored"]
fn java_vm_export_test_operations() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATIONS);
}

#[test]
#[ignore = "Java VM parity — TestOperators.java — run with --ignored"]
fn java_vm_export_test_operators() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_OPERATORS);
}

#[test]
#[ignore = "Java VM parity — TestReference.java — run with --ignored"]
fn java_vm_export_test_reference() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_REFERENCE);
}

#[test]
#[ignore = "Java VM parity — TestSet.java — run with --ignored"]
fn java_vm_export_test_set() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_SET);
}

#[test]
#[ignore = "Java VM parity — TestString.java — run with --ignored"]
fn java_vm_export_test_string() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_STRING);
}

#[test]
#[ignore = "Java VM parity — TestSwitch.java — run with --ignored"]
fn java_vm_export_test_switch() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_SWITCH);
}

#[test]
#[ignore = "Java VM parity — TestSystem.java — run with --ignored"]
fn java_vm_export_test_system() {
    run_cases(cases_generated::VM_JAVA_CASES_TEST_SYSTEM);
}

