mod cfg_flags;
mod expr;
mod lexer_rules;
mod stmt;
mod tokens;
mod r#type;

use sipha::prelude::*;
use std::sync::OnceLock;

static BUILT: OnceLock<BuiltGraph> = OnceLock::new();

/// Lazily-built grammar graph for this crate.
///
/// Enable Cargo feature `grammar-v4-only` to specialize the graph for [`crate::parse::Version::V4`]
/// / [`crate::parse::Version::VNext`] only (fewer flag checks in generated bytecode).
pub fn built_graph() -> &'static BuiltGraph {
    BUILT.get_or_init(|| {
        let mut g = GrammarBuilder::new();
        g.allow_rule_cycles(true);
        g.set_trivia_rule("trivia");

        stmt::define(&mut g);
        tokens::define(&mut g);
        r#type::define(&mut g);
        expr::define(&mut g);

        g.finish().expect("leekscript grammar should build")
    })
}
