//! Registered sipha grammar rule names (PEG rules) for LeekScript.
//!
//! Use [`GRule`] with [`GrammarRuleName`](sipha::types::GrammarRuleName) via
//! [`GrammarBuilder::call_rule`](sipha::prelude::GrammarBuilder::call_rule),
//! [`parser_rule`](sipha::prelude::GrammarBuilder::parser_rule)(`rule.as_str()`, …), etc.

use sipha::types::GrammarRuleName;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GRule {
    AccessModifier,
    Additive,
    AnonFunctionExpr,
    ArgList,
    ArgListOpt,
    ArrayExpr,
    Arrow,
    Assign,
    AssignOp,
    AssignOpGt,
    AssignOpLt,
    AssignOpStar,
    BitwiseBitand,
    BitwiseOr,
    BitwiseXor,
    Block,
    BlockComment,
    BracketIntervalBody,
    BracketListOrMapInner,
    BreakContinueLevel,
    BreakStmt,
    CallExprSuffix,
    ClassBody,
    ClassDecl,
    ClassMember,
    Colon,
    Comma,
    ConstDecl,
    ContinueStmt,
    DeclTemplateParams,
    DoWhileStmt,
    Dot,
    Dotdot,
    ElseStmt,
    Eq,
    Equality,
    ExportStmt,
    Expr,
    FnParamCore,
    ForLoopVar,
    ForStmt,
    FunctionDecl,
    FunctionFnParam,
    GenericFunctionArgs,
    GenericMapArgs,
    GenericTypeArgs,
    GlobalDecl,
    GotoStmt,
    Ident,
    IfExpr,
    IfStmt,
    ImportStmt,
    IncludeStmt,
    IndexExprSuffix,
    Infinity,
    IntervalClosingBracket,
    IntervalRbracketExpr,
    IsCompare,
    KwAbstract,
    KwAny,
    KwArray,
    KwAs,
    KwAwait,
    KwBoolean,
    KwBreak,
    KwByte,
    KwCase,
    KwCatch,
    KwChar,
    KwClass,
    KwClassType,
    KwConst,
    KwConstructor,
    KwContinue,
    KwDefault,
    KwDo,
    KwDouble,
    KwElse,
    KwEnum,
    KwEval,
    KwExport,
    KwExtends,
    KwFalse,
    KwFinal,
    KwFinally,
    KwFloat,
    KwFor,
    KwFunction,
    KwFunctionType,
    KwGlobal,
    KwGoto,
    KwIf,
    KwImplements,
    KwImport,
    KwIn,
    KwInclude,
    KwInstanceof,
    KwInt,
    KwInteger,
    KwInterface,
    KwIntervalType,
    KwIs,
    KwLet,
    KwLong,
    KwMap,
    KwMatch,
    KwNative,
    KwNew,
    KwNot,
    KwNull,
    KwObject,
    KwPackage,
    KwPrivate,
    KwProtected,
    KwPublic,
    KwReal,
    KwReturn,
    KwSetType,
    KwShort,
    KwStatic,
    KwStringType,
    KwSuper,
    KwSwitch,
    KwSynchronized,
    KwThis,
    KwThrow,
    KwThrows,
    KwTransient,
    KwTrue,
    KwTry,
    KwTypeof,
    KwVar,
    KwVoid,
    KwVolatile,
    KwWhile,
    KwWith,
    KwXor,
    KwYield,
    LambdaExpr,
    LambdaHead,
    LambdaParam,
    LambdaReturnType,
    LambdaTypeKwA,
    LambdaTypeKwI,
    LambdaTypeKwS,
    LambdaTypePrimaryNoIdent,
    Lbrace,
    Lbracket,
    LineComment,
    LogicalAnd,
    LogicalXor,
    Lparen,
    LsType,
    MatchCase,
    MatchStmt,
    MemberExprSuffix,
    MethodFnParam,
    Multiplicative,
    Name,
    NewExpr,
    NotIn,
    Number,
    ObjectExpr,
    OpAndAnd,
    OpAndWord,
    OpAt,
    OpBackslash,
    OpBackslashEq,
    OpBang,
    OpBitand,
    OpBitandEq,
    OpBitor,
    OpBitorEq,
    OpBitxor,
    OpBitxorEq,
    OpCoalesce,
    OpCoalesceEq,
    OpEqeq,
    OpEqeqeq,
    OpGt,
    OpGte,
    OpLt,
    OpLte,
    OpMinus,
    OpMinusEq,
    OpMinusminus,
    OpNoteq,
    OpNoteqeq,
    OpOrOr,
    OpOrWord,
    OpPercent,
    OpPercentEq,
    OpPlus,
    OpPlusEq,
    OpPlusplus,
    OpQuestion,
    OpShl,
    OpShlEq,
    OpShr,
    OpShrEq,
    OpSlash,
    OpSlashEq,
    OpStar,
    OpStarEq,
    OpStarStar,
    OpStarStarEq,
    OpTilde,
    OpTripleShl,
    OpTripleShlEq,
    OpUshr,
    OpUshrEq,
    OrCoalesce,
    PackageStmt,
    Param,
    ParenExpr,
    Pi,
    Postfix,
    PostfixIncrSuffix,
    PostfixSuffix,
    PostfixWithAs,
    Power,
    Primary,
    PrimaryFallback,
    PrimaryLparen,
    Rbrace,
    Rbracket,
    Relational,
    ReturnStmt,
    Rparen,
    Semi,
    SetExpr,
    Shift,
    Start,
    Stmt,
    StmtEmptyStatement,
    StmtExprStatement,
    StmtOrBlock,
    String,
    SwitchArm,
    SwitchStmt,
    Ternary,
    ThrowStmt,
    TopLevelSync,
    Trivia,
    TryStmt,
    TypeGt,
    TypeNullable,
    TypePrimary,
    TypeUnion,
    TypedVarDeclItems,
    Unary,
    UnaryMinusPrefixed,
    UnaryPlusPrefixed,
    VarDecl,
    VarDeclItems,
    WhileStmt,
    Ws,
}

impl GRule {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AccessModifier => "access_modifier",
            Self::Additive => "additive",
            Self::AnonFunctionExpr => "anon_function_expr",
            Self::ArgList => "arg_list",
            Self::ArgListOpt => "arg_list_opt",
            Self::ArrayExpr => "array_expr",
            Self::Arrow => "arrow",
            Self::Assign => "assign",
            Self::AssignOp => "assign_op",
            Self::AssignOpGt => "assign_op_gt",
            Self::AssignOpLt => "assign_op_lt",
            Self::AssignOpStar => "assign_op_star",
            Self::BitwiseBitand => "bitwise_bitand",
            Self::BitwiseOr => "bitwise_or",
            Self::BitwiseXor => "bitwise_xor",
            Self::Block => "block",
            Self::BlockComment => "block_comment",
            Self::BracketIntervalBody => "bracket_interval_body",
            Self::BracketListOrMapInner => "bracket_list_or_map_inner",
            Self::BreakContinueLevel => "break_continue_level",
            Self::BreakStmt => "break_stmt",
            Self::CallExprSuffix => "call_expr_suffix",
            Self::ClassBody => "class_body",
            Self::ClassDecl => "class_decl",
            Self::ClassMember => "class_member",
            Self::Colon => "colon",
            Self::Comma => "comma",
            Self::ConstDecl => "const_decl",
            Self::ContinueStmt => "continue_stmt",
            Self::DeclTemplateParams => "decl_template_params",
            Self::DoWhileStmt => "do_while_stmt",
            Self::Dot => "dot",
            Self::Dotdot => "dotdot",
            Self::ElseStmt => "else_stmt",
            Self::Eq => "eq",
            Self::Equality => "equality",
            Self::ExportStmt => "export_stmt",
            Self::Expr => "expr",
            Self::FnParamCore => "fn_param_core",
            Self::ForLoopVar => "for_loop_var",
            Self::ForStmt => "for_stmt",
            Self::FunctionDecl => "function_decl",
            Self::FunctionFnParam => "function_fn_param",
            Self::GenericFunctionArgs => "generic_function_args",
            Self::GenericMapArgs => "generic_map_args",
            Self::GenericTypeArgs => "generic_type_args",
            Self::GlobalDecl => "global_decl",
            Self::GotoStmt => "goto_stmt",
            Self::Ident => "ident",
            Self::IfExpr => "if_expr",
            Self::IfStmt => "if_stmt",
            Self::ImportStmt => "import_stmt",
            Self::IncludeStmt => "include_stmt",
            Self::IndexExprSuffix => "index_expr_suffix",
            Self::Infinity => "infinity",
            Self::IntervalClosingBracket => "interval_closing_bracket",
            Self::IntervalRbracketExpr => "interval_rbracket_expr",
            Self::IsCompare => "is_compare",
            Self::KwAbstract => "kw_abstract",
            Self::KwAny => "kw_any",
            Self::KwArray => "kw_array",
            Self::KwAs => "kw_as",
            Self::KwAwait => "kw_await",
            Self::KwBoolean => "kw_boolean",
            Self::KwBreak => "kw_break",
            Self::KwByte => "kw_byte",
            Self::KwCase => "kw_case",
            Self::KwCatch => "kw_catch",
            Self::KwChar => "kw_char",
            Self::KwClass => "kw_class",
            Self::KwClassType => "kw_class_type",
            Self::KwConst => "kw_const",
            Self::KwConstructor => "kw_constructor",
            Self::KwContinue => "kw_continue",
            Self::KwDefault => "kw_default",
            Self::KwDo => "kw_do",
            Self::KwDouble => "kw_double",
            Self::KwElse => "kw_else",
            Self::KwEnum => "kw_enum",
            Self::KwEval => "kw_eval",
            Self::KwExport => "kw_export",
            Self::KwExtends => "kw_extends",
            Self::KwFalse => "kw_false",
            Self::KwFinal => "kw_final",
            Self::KwFinally => "kw_finally",
            Self::KwFloat => "kw_float",
            Self::KwFor => "kw_for",
            Self::KwFunction => "kw_function",
            Self::KwFunctionType => "kw_function_type",
            Self::KwGlobal => "kw_global",
            Self::KwGoto => "kw_goto",
            Self::KwIf => "kw_if",
            Self::KwImplements => "kw_implements",
            Self::KwImport => "kw_import",
            Self::KwIn => "kw_in",
            Self::KwInclude => "kw_include",
            Self::KwInstanceof => "kw_instanceof",
            Self::KwInt => "kw_int",
            Self::KwInteger => "kw_integer",
            Self::KwInterface => "kw_interface",
            Self::KwIntervalType => "kw_interval_type",
            Self::KwIs => "kw_is",
            Self::KwLet => "kw_let",
            Self::KwLong => "kw_long",
            Self::KwMap => "kw_map",
            Self::KwMatch => "kw_match",
            Self::KwNative => "kw_native",
            Self::KwNew => "kw_new",
            Self::KwNot => "kw_not",
            Self::KwNull => "kw_null",
            Self::KwObject => "kw_object",
            Self::KwPackage => "kw_package",
            Self::KwPrivate => "kw_private",
            Self::KwProtected => "kw_protected",
            Self::KwPublic => "kw_public",
            Self::KwReal => "kw_real",
            Self::KwReturn => "kw_return",
            Self::KwSetType => "kw_set_type",
            Self::KwShort => "kw_short",
            Self::KwStatic => "kw_static",
            Self::KwStringType => "kw_string_type",
            Self::KwSuper => "kw_super",
            Self::KwSwitch => "kw_switch",
            Self::KwSynchronized => "kw_synchronized",
            Self::KwThis => "kw_this",
            Self::KwThrow => "kw_throw",
            Self::KwThrows => "kw_throws",
            Self::KwTransient => "kw_transient",
            Self::KwTrue => "kw_true",
            Self::KwTry => "kw_try",
            Self::KwTypeof => "kw_typeof",
            Self::KwVar => "kw_var",
            Self::KwVoid => "kw_void",
            Self::KwVolatile => "kw_volatile",
            Self::KwWhile => "kw_while",
            Self::KwWith => "kw_with",
            Self::KwXor => "kw_xor",
            Self::KwYield => "kw_yield",
            Self::LambdaExpr => "lambda_expr",
            Self::LambdaHead => "lambda_head",
            Self::LambdaParam => "lambda_param",
            Self::LambdaReturnType => "lambda_return_type",
            Self::LambdaTypeKwA => "lambda_type_kw_a",
            Self::LambdaTypeKwI => "lambda_type_kw_i",
            Self::LambdaTypeKwS => "lambda_type_kw_s",
            Self::LambdaTypePrimaryNoIdent => "lambda_type_primary_no_ident",
            Self::Lbrace => "lbrace",
            Self::Lbracket => "lbracket",
            Self::LineComment => "line_comment",
            Self::LogicalAnd => "logical_and",
            Self::LogicalXor => "logical_xor",
            Self::Lparen => "lparen",
            Self::LsType => "ls_type",
            Self::MatchCase => "match_case",
            Self::MatchStmt => "match_stmt",
            Self::MemberExprSuffix => "member_expr_suffix",
            Self::MethodFnParam => "method_fn_param",
            Self::Multiplicative => "multiplicative",
            Self::Name => "name",
            Self::NewExpr => "new_expr",
            Self::NotIn => "not_in",
            Self::Number => "number",
            Self::ObjectExpr => "object_expr",
            Self::OpAndAnd => "op_and_and",
            Self::OpAndWord => "op_and_word",
            Self::OpAt => "op_at",
            Self::OpBackslash => "op_backslash",
            Self::OpBackslashEq => "op_backslash_eq",
            Self::OpBang => "op_bang",
            Self::OpBitand => "op_bitand",
            Self::OpBitandEq => "op_bitand_eq",
            Self::OpBitor => "op_bitor",
            Self::OpBitorEq => "op_bitor_eq",
            Self::OpBitxor => "op_bitxor",
            Self::OpBitxorEq => "op_bitxor_eq",
            Self::OpCoalesce => "op_coalesce",
            Self::OpCoalesceEq => "op_coalesce_eq",
            Self::OpEqeq => "op_eqeq",
            Self::OpEqeqeq => "op_eqeqeq",
            Self::OpGt => "op_gt",
            Self::OpGte => "op_gte",
            Self::OpLt => "op_lt",
            Self::OpLte => "op_lte",
            Self::OpMinus => "op_minus",
            Self::OpMinusEq => "op_minus_eq",
            Self::OpMinusminus => "op_minusminus",
            Self::OpNoteq => "op_noteq",
            Self::OpNoteqeq => "op_noteqeq",
            Self::OpOrOr => "op_or_or",
            Self::OpOrWord => "op_or_word",
            Self::OpPercent => "op_percent",
            Self::OpPercentEq => "op_percent_eq",
            Self::OpPlus => "op_plus",
            Self::OpPlusEq => "op_plus_eq",
            Self::OpPlusplus => "op_plusplus",
            Self::OpQuestion => "op_question",
            Self::OpShl => "op_shl",
            Self::OpShlEq => "op_shl_eq",
            Self::OpShr => "op_shr",
            Self::OpShrEq => "op_shr_eq",
            Self::OpSlash => "op_slash",
            Self::OpSlashEq => "op_slash_eq",
            Self::OpStar => "op_star",
            Self::OpStarEq => "op_star_eq",
            Self::OpStarStar => "op_star_star",
            Self::OpStarStarEq => "op_star_star_eq",
            Self::OpTilde => "op_tilde",
            Self::OpTripleShl => "op_triple_shl",
            Self::OpTripleShlEq => "op_triple_shl_eq",
            Self::OpUshr => "op_ushr",
            Self::OpUshrEq => "op_ushr_eq",
            Self::OrCoalesce => "or_coalesce",
            Self::PackageStmt => "package_stmt",
            Self::Param => "param",
            Self::ParenExpr => "paren_expr",
            Self::Pi => "pi",
            Self::Postfix => "postfix",
            Self::PostfixIncrSuffix => "postfix_incr_suffix",
            Self::PostfixSuffix => "postfix_suffix",
            Self::PostfixWithAs => "postfix_with_as",
            Self::Power => "power",
            Self::Primary => "primary",
            Self::PrimaryFallback => "primary_fallback",
            Self::PrimaryLparen => "primary_lparen",
            Self::Rbrace => "rbrace",
            Self::Rbracket => "rbracket",
            Self::Relational => "relational",
            Self::ReturnStmt => "return_stmt",
            Self::Rparen => "rparen",
            Self::Semi => "semi",
            Self::SetExpr => "set_expr",
            Self::Shift => "shift",
            Self::Start => "start",
            Self::Stmt => "stmt",
            Self::StmtEmptyStatement => "stmt_empty_statement",
            Self::StmtExprStatement => "stmt_expr_statement",
            Self::StmtOrBlock => "stmt_or_block",
            Self::String => "string",
            Self::SwitchArm => "switch_arm",
            Self::SwitchStmt => "switch_stmt",
            Self::Ternary => "ternary",
            Self::ThrowStmt => "throw_stmt",
            Self::TopLevelSync => "top_level_sync",
            Self::Trivia => "trivia",
            Self::TryStmt => "try_stmt",
            Self::TypeGt => "type_gt",
            Self::TypeNullable => "type_nullable",
            Self::TypePrimary => "type_primary",
            Self::TypeUnion => "type_union",
            Self::TypedVarDeclItems => "typed_var_decl_items",
            Self::Unary => "unary",
            Self::UnaryMinusPrefixed => "unary_minus_prefixed",
            Self::UnaryPlusPrefixed => "unary_plus_prefixed",
            Self::VarDecl => "var_decl",
            Self::VarDeclItems => "var_decl_items",
            Self::WhileStmt => "while_stmt",
            Self::Ws => "ws",
        }
    }
}

impl GrammarRuleName for GRule {
    fn rule_name(self) -> &'static str {
        self.as_str()
    }
}

