use std::fmt;

use sipha::SyntaxKinds;

/// CST node and token kinds for LeekScript.
///
/// Declaration order defines `SyntaxKind` discriminants; do not rely on numeric values across releases.
///
/// [`Display`](std::fmt::Display) and [`K::as_str`](K::as_str) use the same stable `SCREAMING_SNAKE`
/// names as sipha S-expression / diff output for this grammar.
#[derive(Debug, Clone, Copy, PartialEq, Eq, SyntaxKinds)]
#[repr(u16)]
pub enum K {
    // Grammar roots
    Root,
    Stmt,
    Expr,

    // CST — structure
    TokenTree,
    ParenExpr,
    Block,

    // CST — statements (jumps / inclusion)
    ReturnStmt,
    BreakStmt,
    ContinueStmt,
    IncludeStmt,
    /// Lone `;` (empty statement), e.g. `;;` or `for (;; )`.
    EmptyStmt,
    /// Zero-width placeholder from sipha recovery (`parse_doc_with_recovery`); marks a parse error.
    ErrorStmt,

    // CST — declarations
    VarDecl,
    FunctionDecl,
    GlobalDecl,
    /// Not implemented in leekscript-java `WordCompiler` (lexer `CONST` only).
    ConstDecl,
    /// Not implemented in leekscript-java `WordCompiler` (lexer `PACKAGE` only).
    PackageStmt,
    /// Not implemented in leekscript-java `WordCompiler` (lexer `IMPORT` only).
    ImportStmt,
    /// Not implemented in leekscript-java `WordCompiler` (lexer `EXPORT` only).
    ExportStmt,
    ClassDecl,
    ClassMember,
    /// One formal parameter: `T name`, `@name`, or `name` (see grammar `fn_param`).
    FnParam,

    // CST — control flow
    IfStmt,
    IfExpr,
    ElseStmt,
    WhileStmt,
    DoWhileStmt,
    ForStmt,
    ForeachStmt,
    /// Not in Java `LexicalParser`; leekscript-rs extension (parsed only when v4).
    MatchStmt,
    SwitchStmt,
    SwitchArm,

    // CST — try / throw / goto (mostly CST-only vs leekscript-java `WordCompiler`)
    /// `try` / `catch` / `finally` — CST only; not implemented in leekscript-java `WordCompiler`.
    TryStmt,
    CatchClause,
    /// Not implemented in leekscript-java `WordCompiler` (lexer `THROW` only).
    ThrowStmt,
    /// Not implemented in leekscript-java `WordCompiler` (lexer `GOTO` only).
    GotoStmt,

    // CST — expressions
    TypeExpr,
    /// `T | U | …` — child `TypeNullableType` nodes and `|` tokens.
    TypeUnionType,
    /// `T` or `T?` — child `TypePrimaryType`, optional `?`.
    TypeNullableType,
    /// One type primary: keyword / `ident` / `Array<…>` / … — see grammar `type_primary`.
    TypePrimaryType,
    BracketMapExpr,
    IntervalExpr,
    AnonFunctionExpr,
    CastExpr,
    CallExpr,
    IndexExpr,
    ArrayExpr,
    ObjectExpr,
    MemberExpr,
    TernaryExpr,
    LambdaExpr,
    NewExpr,
    SetExpr,
    ThisExpr,
    SuperExpr,
    ClassRefExpr,
    /// `Class` / `Array` / `Array<T>` as expression operands (e.g. `instanceof Class`).
    BuiltinTypeNameExpr,
    /// Lowercase `string` as the built-in stringify callable (`string(x)`), distinct from type `string`.
    BuiltinStringifyExpr,
    BinaryExpr,
    UnaryExpr,

    // Tokens — extended operators (see leekscript-java `Operators`)
    Coalesce,
    CoalesceEq,
    StarStar,
    StarStarEq,
    Backslash,
    BackslashEq,
    Shl,
    Shr,
    UShr,
    ShlEq,
    ShrEq,
    UShrEq,
    /// `<<<` — present in leekscript-java `LexicalParser` operator list (no `Operators` mapping).
    TripleShl,
    /// `<<<=` — same as above.
    TripleShlEq,
    BitAnd,
    BitOr,
    BitXor,
    BitAndEq,
    BitOrEq,
    BitXorEq,
    Question,
    InstanceofKw,
    XorKw,
    NotKw,

    // Tokens — literals
    Ident,
    Number,
    String,
    Pi,
    Infinity,
    TrueKw,
    FalseKw,
    NullKw,

    // Tokens — language keywords
    VarKw,
    LetKw,
    BreakKw,
    ContinueKw,
    DoKw,
    ReturnKw,
    FunctionKw,
    IfKw,
    ElseKw,
    ForKw,
    WhileKw,
    IncludeKw,
    MatchKw,
    InKw,
    AsKw,
    ClassKw,
    NewKw,
    ThisKw,
    SuperKw,
    SwitchKw,
    CaseKw,
    DefaultKw,
    GlobalKw,
    ExtendsKw,
    PublicKw,
    PrivateKw,
    ProtectedKw,
    StaticKw,
    FinalKw,
    ConstructorKw,
    IsKw,
    VoidKw,
    BooleanKw,
    AnyKw,
    IntegerKw,
    RealKw,
    StringTypeKw,
    ClassTypeKw,
    ObjectKw,
    ArrayKw,
    SetTypeKw,
    MapKw,
    FunctionTypeKw,
    /// Type `Interval<T>` (`T` is `integer` or `real` for bounds).
    IntervalKw,

    // Java `LexicalParser` v3 reserved words — mostly lexer-only in leekscript-java (no
    // `WordCompiler` support yet); included here for token/CST parity.
    AbstractKw,
    AwaitKw,
    ByteKw,
    CatchKw,
    CharKw,
    ConstKw,
    DoubleKw,
    EnumKw,
    EvalKw,
    ExportKw,
    FinallyKw,
    FloatKw,
    GotoKw,
    ImplementsKw,
    ImportKw,
    IntKw,
    InterfaceKw,
    LongKw,
    NativeKw,
    PackageKw,
    ShortKw,
    SynchronizedKw,
    ThrowKw,
    ThrowsKw,
    TransientKw,
    TryKw,
    TypeofKw,
    VolatileKw,
    WithKw,
    YieldKw,

    // Tokens — punctuation / operators
    Semi,
    Comma,
    Colon,
    Dot,
    DotDot,
    Arrow,
    Eq,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    EqEq,
    NotEq,
    EqEqEq,
    NotEqEq,
    Lt,
    Lte,
    Gt,
    Gte,
    AndAnd,
    OrOr,
    Bang,
    Tilde,
    PlusPlus,
    MinusMinus,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Operator,

    // Trivia
    Trivia,
    Ws,
    LineComment,
    BlockComment,
}

impl K {
    /// Stable uppercase label (matches S-expression / diff output for this grammar).
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Root => "ROOT",
            Self::Stmt => "STMT",
            Self::Expr => "EXPR",
            Self::TokenTree => "TOKEN_TREE",
            Self::ParenExpr => "PAREN_EXPR",
            Self::Block => "BLOCK",
            Self::ReturnStmt => "RETURN_STMT",
            Self::BreakStmt => "BREAK_STMT",
            Self::ContinueStmt => "CONTINUE_STMT",
            Self::IncludeStmt => "INCLUDE_STMT",
            Self::EmptyStmt => "EMPTY_STMT",
            Self::ErrorStmt => "ERROR_STMT",
            Self::VarDecl => "VAR_DECL",
            Self::FunctionDecl => "FUNCTION_DECL",
            Self::GlobalDecl => "GLOBAL_DECL",
            Self::ConstDecl => "CONST_DECL",
            Self::PackageStmt => "PACKAGE_STMT",
            Self::ImportStmt => "IMPORT_STMT",
            Self::ExportStmt => "EXPORT_STMT",
            Self::ClassDecl => "CLASS_DECL",
            Self::ClassMember => "CLASS_MEMBER",
            Self::FnParam => "FN_PARAM",
            Self::IfStmt => "IF_STMT",
            Self::IfExpr => "IF_EXPR",
            Self::ElseStmt => "ELSE_STMT",
            Self::WhileStmt => "WHILE_STMT",
            Self::DoWhileStmt => "DO_WHILE_STMT",
            Self::ForStmt => "FOR_STMT",
            Self::ForeachStmt => "FOREACH_STMT",
            Self::MatchStmt => "MATCH_STMT",
            Self::SwitchStmt => "SWITCH_STMT",
            Self::SwitchArm => "SWITCH_ARM",
            Self::TryStmt => "TRY_STMT",
            Self::CatchClause => "CATCH_CLAUSE",
            Self::ThrowStmt => "THROW_STMT",
            Self::GotoStmt => "GOTO_STMT",
            Self::TypeExpr => "TYPE_EXPR",
            Self::TypeUnionType => "TYPE_UNION_TYPE",
            Self::TypeNullableType => "TYPE_NULLABLE_TYPE",
            Self::TypePrimaryType => "TYPE_PRIMARY_TYPE",
            Self::BracketMapExpr => "BRACKET_MAP_EXPR",
            Self::IntervalExpr => "INTERVAL_EXPR",
            Self::AnonFunctionExpr => "ANON_FUNCTION_EXPR",
            Self::CastExpr => "CAST_EXPR",
            Self::CallExpr => "CALL_EXPR",
            Self::IndexExpr => "INDEX_EXPR",
            Self::ArrayExpr => "ARRAY_EXPR",
            Self::ObjectExpr => "OBJECT_EXPR",
            Self::MemberExpr => "MEMBER_EXPR",
            Self::TernaryExpr => "TERNARY_EXPR",
            Self::LambdaExpr => "LAMBDA_EXPR",
            Self::NewExpr => "NEW_EXPR",
            Self::SetExpr => "SET_EXPR",
            Self::ThisExpr => "THIS_EXPR",
            Self::SuperExpr => "SUPER_EXPR",
            Self::ClassRefExpr => "CLASS_REF_EXPR",
            Self::BuiltinTypeNameExpr => "BUILTIN_TYPE_NAME_EXPR",
            Self::BuiltinStringifyExpr => "BUILTIN_STRINGIFY_EXPR",
            Self::BinaryExpr => "BINARY_EXPR",
            Self::UnaryExpr => "UNARY_EXPR",
            Self::Coalesce => "COALESCE",
            Self::CoalesceEq => "COALESCE_EQ",
            Self::StarStar => "STARSTAR",
            Self::StarStarEq => "STARSTAR_EQ",
            Self::Backslash => "BACKSLASH",
            Self::BackslashEq => "BACKSLASH_EQ",
            Self::Shl => "SHL",
            Self::Shr => "SHR",
            Self::UShr => "USHR",
            Self::ShlEq => "SHL_EQ",
            Self::ShrEq => "SHR_EQ",
            Self::UShrEq => "USHR_EQ",
            Self::TripleShl => "TRIPLE_SHL",
            Self::TripleShlEq => "TRIPLE_SHL_EQ",
            Self::BitAnd => "BITAND",
            Self::BitOr => "BITOR",
            Self::BitXor => "BITXOR",
            Self::BitAndEq => "BITAND_EQ",
            Self::BitOrEq => "BITOR_EQ",
            Self::BitXorEq => "BITXOR_EQ",
            Self::Question => "QUESTION",
            Self::InstanceofKw => "INSTANCEOF",
            Self::XorKw => "XOR",
            Self::NotKw => "NOT",
            Self::Ident => "IDENT",
            Self::Number => "NUMBER",
            Self::String => "STRING",
            Self::Pi => "PI",
            Self::Infinity => "INFINITY",
            Self::TrueKw => "TRUE",
            Self::FalseKw => "FALSE",
            Self::NullKw => "NULL",
            Self::VarKw => "VAR",
            Self::LetKw => "LET",
            Self::BreakKw => "BREAK",
            Self::ContinueKw => "CONTINUE",
            Self::DoKw => "DO",
            Self::ReturnKw => "RETURN",
            Self::FunctionKw => "FUNCTION",
            Self::IfKw => "IF",
            Self::ElseKw => "ELSE",
            Self::ForKw => "FOR",
            Self::WhileKw => "WHILE",
            Self::IncludeKw => "INCLUDE",
            Self::MatchKw => "MATCH",
            Self::InKw => "IN",
            Self::AsKw => "AS",
            Self::ClassKw => "CLASS",
            Self::NewKw => "NEW",
            Self::ThisKw => "THIS_KW",
            Self::SuperKw => "SUPER_KW",
            Self::SwitchKw => "SWITCH_KW",
            Self::CaseKw => "CASE_KW",
            Self::DefaultKw => "DEFAULT_KW",
            Self::GlobalKw => "GLOBAL_KW",
            Self::ExtendsKw => "EXTENDS_KW",
            Self::PublicKw => "PUBLIC_KW",
            Self::PrivateKw => "PRIVATE_KW",
            Self::ProtectedKw => "PROTECTED_KW",
            Self::StaticKw => "STATIC_KW",
            Self::FinalKw => "FINAL_KW",
            Self::ConstructorKw => "CONSTRUCTOR_KW",
            Self::IsKw => "IS_KW",
            Self::VoidKw => "VOID_KW",
            Self::BooleanKw => "BOOLEAN_KW",
            Self::AnyKw => "ANY_KW",
            Self::IntegerKw => "INTEGER_KW",
            Self::RealKw => "REAL_KW",
            Self::StringTypeKw => "STRING_TYPE_KW",
            Self::ClassTypeKw => "CLASS_TYPE_KW",
            Self::ObjectKw => "OBJECT_KW",
            Self::ArrayKw => "ARRAY_KW",
            Self::SetTypeKw => "SET_TYPE_KW",
            Self::MapKw => "MAP_KW",
            Self::FunctionTypeKw => "FUNCTION_TYPE_KW",
            Self::IntervalKw => "INTERVAL_KW",
            Self::AbstractKw => "ABSTRACT_KW",
            Self::AwaitKw => "AWAIT_KW",
            Self::ByteKw => "BYTE_KW",
            Self::CatchKw => "CATCH_KW",
            Self::CharKw => "CHAR_KW",
            Self::ConstKw => "CONST_KW",
            Self::DoubleKw => "DOUBLE_KW",
            Self::EnumKw => "ENUM_KW",
            Self::EvalKw => "EVAL_KW",
            Self::ExportKw => "EXPORT_KW",
            Self::FinallyKw => "FINALLY_KW",
            Self::FloatKw => "FLOAT_KW",
            Self::GotoKw => "GOTO_KW",
            Self::ImplementsKw => "IMPLEMENTS_KW",
            Self::ImportKw => "IMPORT_KW",
            Self::IntKw => "INT_KW",
            Self::InterfaceKw => "INTERFACE_KW",
            Self::LongKw => "LONG_KW",
            Self::NativeKw => "NATIVE_KW",
            Self::PackageKw => "PACKAGE_KW",
            Self::ShortKw => "SHORT_KW",
            Self::SynchronizedKw => "SYNCHRONIZED_KW",
            Self::ThrowKw => "THROW_KW",
            Self::ThrowsKw => "THROWS_KW",
            Self::TransientKw => "TRANSIENT_KW",
            Self::TryKw => "TRY_KW",
            Self::TypeofKw => "TYPEOF_KW",
            Self::VolatileKw => "VOLATILE_KW",
            Self::WithKw => "WITH_KW",
            Self::YieldKw => "YIELD_KW",
            Self::Semi => "SEMI",
            Self::Comma => "COMMA",
            Self::Colon => "COLON",
            Self::Dot => "DOT",
            Self::DotDot => "DOT_DOT",
            Self::Arrow => "ARROW",
            Self::Eq => "EQ",
            Self::Plus => "PLUS",
            Self::Minus => "MINUS",
            Self::Star => "STAR",
            Self::Slash => "SLASH",
            Self::Percent => "PERCENT",
            Self::PlusEq => "PLUS_EQ",
            Self::MinusEq => "MINUS_EQ",
            Self::StarEq => "STAR_EQ",
            Self::SlashEq => "SLASH_EQ",
            Self::PercentEq => "PERCENT_EQ",
            Self::EqEq => "EQEQ",
            Self::NotEq => "NOTEQ",
            Self::EqEqEq => "EQEQEQ",
            Self::NotEqEq => "NOTEQEQ",
            Self::Lt => "LT",
            Self::Lte => "LTE",
            Self::Gt => "GT",
            Self::Gte => "GTE",
            Self::AndAnd => "ANDAND",
            Self::OrOr => "OROR",
            Self::Bang => "BANG",
            Self::Tilde => "TILDE",
            Self::PlusPlus => "PLUSPLUS",
            Self::MinusMinus => "MINUSMINUS",
            Self::LParen => "LPAREN",
            Self::RParen => "RPAREN",
            Self::LBracket => "LBRACKET",
            Self::RBracket => "RBRACKET",
            Self::LBrace => "LBRACE",
            Self::RBrace => "RBRACE",
            Self::Operator => "OPERATOR",
            Self::Trivia => "TRIVIA",
            Self::Ws => "WS",
            Self::LineComment => "LINE_COMMENT",
            Self::BlockComment => "BLOCK_COMMENT",
        }
    }
}

impl fmt::Display for K {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
